// AUTO-DERIVED from the real test files (hub/tests/*.test.ts) on 2026-06-26.
// Source of truth: each test's describe/it title. Pure files form the `npm run test:ci`
// gate (414 tests); live files (37) need DB/HubSpot/Stripe keys and skip in CI.
// Organized by the suite taxonomy in lib/dev/suites.ts. Do not hand-edit row text;
// regenerate from the suite when tests change.

export type TestKind = "pure" | "live";

export interface TestRow {
  /** The `it(...)` assertion title - what the test checks. */
  test: string;
  /** The enclosing `describe(...)` block - the contract/area it proves. */
  area: string;
  /** Test file under hub/tests/. */
  file: string;
  /** pure = no services, always in CI; live = needs DB/HubSpot/Stripe, skips gracefully. */
  kind: TestKind;
}

export interface TestGroup {
  id: string;
  label: string;
  domain: string;
  /** npm script that runs (a superset of) this group. */
  script: string;
  rows: TestRow[];
}

export const TEST_GROUPS: TestGroup[] = [
  {
    id: "data",
    label: "Data",
    domain: "Generation, fixtures, identity resolution & external data sources",
    script: "npm run test:data",
    rows: [
      { test: "is deterministic: same seed → byte-identical dataset", area: "seed generator", file: "seed.test.ts", kind: "pure" },
      { test: "changes with the seed", area: "seed generator", file: "seed.test.ts", kind: "pure" },
      { test: "passes every invariant at the default size", area: "seed generator", file: "seed.test.ts", kind: "pure" },
      { test: "passes invariants across a range of seeds and sizes", area: "seed generator", file: "seed.test.ts", kind: "pure" },
      { test: "records all 15 deliberate edge cases", area: "seed generator", file: "seed.test.ts", kind: "pure" },
      { test: "makes income the master conversion variable ($160K+ converts highest)", area: "realism of the modeled funnel", file: "seed.test.ts", kind: "pure" },
      { test: "spreads families across multiple states with Texas as the home market", area: "realism of the modeled funnel", file: "seed.test.ts", kind: "pure" },
      { test: "models a $365K budget with a real over-plan workstream", area: "realism of the modeled funnel", file: "seed.test.ts", kind: "pure" },
      { test: "labels every stood-in record honestly", area: "realism of the modeled funnel", file: "seed.test.ts", kind: "pure" },
      { test: "threads UTM campaigns from CRM → Meta → GA4", area: "realism of the modeled funnel", file: "seed.test.ts", kind: "pure" },
      { test: "models Meta over-reporting vs CRM (attribution gap)", area: "realism of the modeled funnel", file: "seed.test.ts", kind: "pure" },
      { test: "uses real API field names on Meta rows", area: "realism of the modeled funnel", file: "seed.test.ts", kind: "pure" },
      { test: "a duplicate family shares a match_key with its original", area: "edge cases are provable", file: "seed.test.ts", kind: "pure" },
      { test: "a Stripe event delivered twice is recorded once in the idempotency ledger", area: "edge cases are provable", file: "seed.test.ts", kind: "pure" },
      { test: "a failed payment is followed by a succeeded retry on the same enrollment", area: "edge cases are provable", file: "seed.test.ts", kind: "pure" },
      { test: "the dual-source feeds collide on match_key (reconciliation has work to do)", area: "edge cases are provable", file: "seed.test.ts", kind: "pure" },
      { test: "a phone-only family resolves to a phone-based match key", area: "edge cases are provable", file: "seed.test.ts", kind: "pure" },
      { test: "no payment crosses program isolation", area: "edge cases are provable", file: "seed.test.ts", kind: "pure" },
      { test: "returns a 64-char sha256 hex when a signal exists", area: "matchKey — dual-source identity resolution", file: "matchkey.test.ts", kind: "pure" },
      { test: "prefers email over phone over name+zip", area: "matchKey — dual-source identity resolution", file: "matchkey.test.ts", kind: "pure" },
      { test: "normalizes email (trim + lowercase)", area: "matchKey — dual-source identity resolution", file: "matchkey.test.ts", kind: "pure" },
      { test: "falls back to phone and normalizes to digits only", area: "matchKey — dual-source identity resolution", file: "matchkey.test.ts", kind: "pure" },
      { test: "ignores too-short phone strings", area: "matchKey — dual-source identity resolution", file: "matchkey.test.ts", kind: "pure" },
      { test: "falls back to name+zip, insensitive to case and surrounding space", area: "matchKey — dual-source identity resolution", file: "matchkey.test.ts", kind: "pure" },
      { test: "requires BOTH name and zip for the fallback", area: "matchKey — dual-source identity resolution", file: "matchkey.test.ts", kind: "pure" },
      { test: "returns null when no usable signal is present", area: "matchKey — dual-source identity resolution", file: "matchkey.test.ts", kind: "pure" },
      { test: "tags key type so a phone never collides with a like-stringed email", area: "matchKey — dual-source identity resolution", file: "matchkey.test.ts", kind: "pure" },
      { test: "is deterministic and distinguishes different identities", area: "matchKey — dual-source identity resolution", file: "matchkey.test.ts", kind: "pure" },
      { test: "exposes a clearly-labeled name", area: "mockConnector", file: "matchkey.test.ts", kind: "pure" },
      { test: "returns seeded, mock-labeled records", area: "mockConnector", file: "matchkey.test.ts", kind: "pure" },
      { test: "filters fetchSince by date", area: "mockConnector", file: "matchkey.test.ts", kind: "pure" },
      { test: "every seeded record resolves to a non-null matchKey", area: "mockConnector", file: "matchkey.test.ts", kind: "pure" },
      { test: "verifyWebhook accepts (mock) and pushUpdate is a no-op", area: "mockConnector", file: "matchkey.test.ts", kind: "pure" },
      { test: "maps app-owned family values onto the existing HubSpot enum vocabulary", area: "seed-hubspot bridge mappings", file: "seed-hubspot.test.ts", kind: "pure" },
      { test: "keeps dry bridge payloads identity-only unless syncFields is requested", area: "seed-hubspot bridge mappings", file: "seed-hubspot.test.ts", kind: "pure" },
      { test: "compacts large counts", area: "formatRows", file: "catalog.test.ts", kind: "pure" },
      { test: "classifies known providers into tiers", area: "providerTier / curateProviders", file: "catalog.test.ts", kind: "pure" },
      { test: "groups and sorts providers by dataset count", area: "providerTier / curateProviders", file: "catalog.test.ts", kind: "pure" },
      { test: "maps API fields and drops empty providers", area: "listProviders", file: "catalog.test.ts", kind: "pure" },
      { test: "normalizes platform totals", area: "getPlatformStats", file: "catalog.test.ts", kind: "pure" },
      { test: "always requests objects and encodes filter[col] params", area: "buildDatasetUrl", file: "opendata.test.ts", kind: "pure" },
      { test: "hits the network once, then serves from cache within TTL", area: "fetchDataset caching", file: "opendata.test.ts", kind: "pure" },
      { test: "refetches once TTL has elapsed", area: "fetchDataset caching", file: "opendata.test.ts", kind: "pure" },
      { test: "falls back to stale cache when a later fetch fails", area: "fetchDataset caching", file: "opendata.test.ts", kind: "pure" },
      { test: "falls back to the fixture when there is no cache and the network fails", area: "fetchDataset caching", file: "opendata.test.ts", kind: "pure" },
      { test: "filters ratings by county and returns null for unknown datasets", area: "openDataFixture", file: "opendata.test.ts", kind: "pure" },
      { test: "computes a weak-district signal from stood-in data", area: "enrichDecisionByCounties (offline via fixture)", file: "opendata.test.ts", kind: "pure" },
      { test: "turns a cautious baseline decision into an approve recommendation when underserved demand is high", area: "enrichDecisionByCounties (offline via fixture)", file: "opendata.test.ts", kind: "pure" },
      { test: "has ~2,000 families and exactly the 112-deposit fall total", area: "seed fixtures — volume & deposit total", file: "seed-fixtures.test.ts", kind: "live" },
      { test: "clicked ~52%, opened ~30%, cold ~16%, strictly monotonic", area: "seed fixtures — engagement tier is the top predictor (52/30/16)", file: "seed-fixtures.test.ts", kind: "live" },
      { test: "the 160K+ slice converts ~25%", area: "seed fixtures — income is the master variable (160K+ ~25% regardless of geo)", file: "seed-fixtures.test.ts", kind: "live" },
      { test: "160K+ converts ~the same in TX and out-of-state", area: "seed fixtures — income is the master variable (160K+ ~25% regardless of geo)", file: "seed-fixtures.test.ts", kind: "live" },
      { test: "TX vs out-of-state is ~50/50", area: "seed fixtures — geo split, channel, grade", file: "seed-fixtures.test.ts", kind: "live" },
      { test: "X is the top converter (~42%); Facebook is the high-volume low-conversion trap", area: "seed fixtures — geo split, channel, grade", file: "seed-fixtures.test.ts", kind: "live" },
      { test: "K-2 is the sweet spot; 9-12 is dead", area: "seed fixtures — geo split, channel, grade", file: "seed-fixtures.test.ts", kind: "live" },
      { test: "T2:T3 ~ 3100:1124 with T2 the dominant cohort", area: "seed fixtures — T2/T3 segments (asserted loosely, ±20%)", file: "seed-fixtures.test.ts", kind: "live" },
      { test: "income_band field parity is below threshold while overall stays healthy", area: "seed fixtures — CRM Ops sync parity (income low, overall healthy)", file: "seed-fixtures.test.ts", kind: "live" },
      { test: "planned + committed both sum to 365,000 and only guerrilla is >10% over plan", area: "seed fixtures — budget reconciles to $365K with guerrilla >10% over", file: "seed-fixtures.test.ts", kind: "live" },
      { test: "a family is enrolled in BOTH programs (RLS-scoped reads, intersected)", area: "seed fixtures — Phase-1 stress cases all present", file: "seed-fixtures.test.ts", kind: "live" },
      { test: "two parent-families share one child (the camp seat counts once)", area: "seed fixtures — Phase-1 stress cases all present", file: "seed-fixtures.test.ts", kind: "live" },
      { test: "a family has two children (spanning the two programs)", area: "seed fixtures — Phase-1 stress cases all present", file: "seed-fixtures.test.ts", kind: "live" },
      { test: "a dual-source duplicate exists (one match_key, two families, two source systems)", area: "seed fixtures — Phase-1 stress cases all present", file: "seed-fixtures.test.ts", kind: "live" },
      { test: "payment stress: duplicate intent is a no-op, refund-then-succeeded does NOT regress", area: "seed fixtures — Phase-1 stress cases all present", file: "seed-fixtures.test.ts", kind: "live" },
      { test: "data-quality queue has a permanent UTM-broken item + an auto-detected sync-drift item", area: "seed fixtures — Phase-1 stress cases all present", file: "seed-fixtures.test.ts", kind: "live" },
      { test: "decisions queue has >=3 open items including an auto-flagged budget-variance decision", area: "seed fixtures — Phase-1 stress cases all present", file: "seed-fixtures.test.ts", kind: "live" },
      { test: "garbled/missing records exist (mojibake names, null income/grade)", area: "seed fixtures — Phase-1 stress cases all present", file: "seed-fixtures.test.ts", kind: "live" },
    ],
  },
  {
    id: "backend",
    label: "Backend & Sync",
    domain: "Sync engine, payments, decision/budget routes, DB isolation & connectors",
    script: "npm run test:backend",
    rows: [
      { test: "rejects missing counties with 400 and does not call Open Data", area: "GET /api/opendata/decision-enrichment", file: "opendata-route.test.ts", kind: "pure" },
      { test: "normalizes counties, forwards optional years, and returns cache headers", area: "GET /api/opendata/decision-enrichment", file: "opendata-route.test.ts", kind: "pure" },
      { test: "returns 502 when enrichment fails", area: "GET /api/opendata/decision-enrichment", file: "opendata-route.test.ts", kind: "pure" },
      { test: "returns 401 before doing agent work when unauthenticated", area: "/api/ask", file: "ask-route.test.ts", kind: "pure" },
      { test: "returns the role-aware agent roster on GET", area: "/api/ask", file: "ask-route.test.ts", kind: "pure" },
      { test: "answers an authenticated leader question with citations and audit metadata", area: "/api/ask", file: "ask-route.test.ts", kind: "pure" },
      { test: "refuses an operator full-queue prompt instead of leaking the queue", area: "/api/ask", file: "ask-route.test.ts", kind: "pure" },
      { test: "validates empty and oversized questions", area: "/api/ask", file: "ask-route.test.ts", kind: "pure" },
      { test: "answers a leadership operating question with citations, actions, and no PII", area: "Ask-the-Hub agents", file: "ask-agents.test.ts", kind: "pure" },
      { test: "refuses exact CAC-by-channel while offering a safer GT Challenge CPQL path", area: "Ask-the-Hub agents", file: "ask-agents.test.ts", kind: "pure" },
      { test: "keeps Operators scoped to coaching instead of the full Decision Queue", area: "Ask-the-Hub agents", file: "ask-agents.test.ts", kind: "pure" },
      { test: "uses Open Data as decision context and reports source confidence", area: "Ask-the-Hub agents", file: "ask-agents.test.ts", kind: "pure" },
      { test: "uses an injected provider for final synthesis over de-identified RAG context", area: "Ask-the-Hub agents", file: "ask-agents.test.ts", kind: "pure" },
      { test: "builds a de-identified context with business facts but no family records", area: "Ask-the-Hub agents", file: "ask-agents.test.ts", kind: "pure" },
      { test: "defines unique business eval cases with expected graph assertions", area: "Ask-the-Hub evals and traceability", file: "ask-evals.test.ts", kind: "pure" },
      { test: "emits node rows with input, expected output, actual output, pass/fail, and citations", area: "Ask-the-Hub evals and traceability", file: "ask-evals.test.ts", kind: "pure" },
      { test: "runs the full deterministic suite and keeps all cases passing", area: "Ask-the-Hub evals and traceability", file: "ask-evals.test.ts", kind: "pure" },
      { test: "records a leadership approval with note and resolution timestamp", area: "Decision Queue transitions", file: "decisions.test.ts", kind: "pure" },
      { test: "normalizes need-info spelling", area: "Decision Queue transitions", file: "decisions.test.ts", kind: "pure" },
      { test: "rejects missing notes and already-decided rows", area: "Decision Queue transitions", file: "decisions.test.ts", kind: "pure" },
      { test: "captures who/when/what for an approval, carrying the status transition", area: "Decision audit trail (buildDecisionEvent)", file: "decisions.test.ts", kind: "pure" },
      { test: "records a need_info round-trip as open -> in_flight", area: "Decision audit trail (buildDecisionEvent)", file: "decisions.test.ts", kind: "pure" },
      { test: "refuses to build an event without a ruling or an actor id", area: "Decision audit trail (buildDecisionEvent)", file: "decisions.test.ts", kind: "pure" },
      { test: "requires Leader role and persists response fields to the decisions table", area: "POST /api/decisions/[id]/decide", file: "decisions.test.ts", kind: "pure" },
      { test: "writes an append-only decision_event audit row with who/when/action", area: "POST /api/decisions/[id]/decide", file: "decisions.test.ts", kind: "pure" },
      { test: "does not write an audit row when the ruling update loses a race (no row updated)", area: "POST /api/decisions/[id]/decide", file: "decisions.test.ts", kind: "pure" },
      { test: "returns 403 before DB access for non-leaders", area: "POST /api/decisions/[id]/decide", file: "decisions.test.ts", kind: "pure" },
      { test: "returns 400 for invalid decision ids before DB access", area: "POST /api/decisions/[id]/decide", file: "decisions.test.ts", kind: "pure" },
      { test: "returns 401 before DB access for unauthenticated callers", area: "POST /api/decisions/[id]/decide", file: "decisions.test.ts", kind: "pure" },
      { test: "returns 404 for unknown decisions and 409 for closed decisions", area: "POST /api/decisions/[id]/decide", file: "decisions.test.ts", kind: "pure" },
      { test: "returns 409 when a concurrent ruling wins before the update", area: "POST /api/decisions/[id]/decide", file: "decisions.test.ts", kind: "pure" },
      { test: "active = anything not decided; history = decided only", area: "Decision Queue read helpers", file: "decisions-queue.test.ts", kind: "pure" },
      { test: "orders active urgent-first, then soonest due, then oldest raised", area: "Decision Queue read helpers", file: "decisions-queue.test.ts", kind: "pure" },
      { test: "badge counts strictly OPEN rows (not in_flight, not decided)", area: "Decision Queue read helpers", file: "decisions-queue.test.ts", kind: "pure" },
      { test: "rolls up stats including budget-at-stake over active rows only", area: "Decision Queue read helpers", file: "decisions-queue.test.ts", kind: "pure" },
      { test: "submittedBy matches the submitter title (the own-status read)", area: "Decision Queue read helpers", file: "decisions-queue.test.ts", kind: "pure" },
      { test: "RBAC read split: Leader sees all, others see only their own submissions", area: "Decision Queue read helpers", file: "decisions-queue.test.ts", kind: "pure" },
      { test: "routes submitters to own-status, not the Leader-only queue", area: "Decision Queue read helpers", file: "decisions-queue.test.ts", kind: "pure" },
      { test: "labels and tones outcomes for both queue + own-status", area: "Decision Queue read helpers", file: "decisions-queue.test.ts", kind: "pure" },
      { test: "shows an Operator only their own decision statuses and leadership responses", area: "My submissions status view", file: "decisions-queue.test.ts", kind: "pure" },
      { test: "does not expose full-queue links or ruling controls", area: "My submissions status view", file: "decisions-queue.test.ts", kind: "pure" },
      { test: "computeSeedParity only counts governed fields and sorts worst-first", area: "CRM Ops · parity view (pure twin of the engine)", file: "crm-ops.test.ts", kind: "pure" },
      { test: "reliability flags read field_authority.expected_unreliable, not a hardcoded list", area: "CRM Ops · parity view (pure twin of the engine)", file: "crm-ops.test.ts", kind: "pure" },
      { test: "a known-unreliable field below threshold does NOT trip the alarm (calm)", area: "CRM Ops · banner alarm semantics (invariant #2)", file: "crm-ops.test.ts", kind: "pure" },
      { test: "a non-expected field below threshold IS the alarm (surprise → red)", area: "CRM Ops · banner alarm semantics (invariant #2)", file: "crm-ops.test.ts", kind: "pure" },
      { test: "no-vanity-hide: overall can read green while a field is visibly below (invariant #5)", area: "CRM Ops · banner alarm semantics (invariant #2)", file: "crm-ops.test.ts", kind: "pure" },
      { test: "isMalformedSource flags missing/sentinel/template sources", area: "CRM Ops · auto-detector (idempotent)", file: "crm-ops.test.ts", kind: "pure" },
      { test: "creates utm + sync + duplicate-identity issues from the snapshot", area: "CRM Ops · auto-detector (idempotent)", file: "crm-ops.test.ts", kind: "pure" },
      { test: "is idempotent: a rerun over unchanged + persisted state opens 0 and resolves 0 (invariant #3)", area: "CRM Ops · auto-detector (idempotent)", file: "crm-ops.test.ts", kind: "pure" },
      { test: "auto-resolves a previously-open auto-issue once its condition clears", area: "CRM Ops · auto-detector (idempotent)", file: "crm-ops.test.ts", kind: "pure" },
      { test: "never touches manual/system issues (no detector signature) on resolve", area: "CRM Ops · auto-detector (idempotent)", file: "crm-ops.test.ts", kind: "pure" },
      { test: "issue descriptions carry field + entity_id only, never raw income/TEFA/child values", area: "CRM Ops · privacy (no PII in issue text — invariant #9)", file: "crm-ops.test.ts", kind: "pure" },
      { test: "reports broken UTM, a 3-hop chain, and names the HubSpot property", area: "CRM Ops · attribution chain (§7b)", file: "crm-ops.test.ts", kind: "pure" },
      { test: "is read-only and labels score→conversion as correlation with n + caveat (Rahman A4)", area: "CRM Ops · lead scoring (read-only, §7c)", file: "crm-ops.test.ts", kind: "pure" },
      { test: "merges detected issues idempotently and derives (not stores) an owner", area: "CRM Ops · data-quality queue + RBAC (invariant #8)", file: "crm-ops.test.ts", kind: "pure" },
      { test: "denies Operators read + act; allows Admin/Leader", area: "CRM Ops · data-quality queue + RBAC (invariant #8)", file: "crm-ops.test.ts", kind: "pure" },
      { test: "denies an Operator the module surface server-side", area: "CRM Ops · rendered page (RBAC + sub-views)", file: "crm-ops.test.ts", kind: "pure" },
      { test: "renders the five sub-views for a Leader", area: "CRM Ops · rendered page (RBAC + sub-views)", file: "crm-ops.test.ts", kind: "pure" },
      { test: "recomputes the $365K total live (not a seed constant)", area: "Budget · reconcile to $365K + column identities (invariants #1, #2)", file: "budget.test.ts", kind: "pure" },
      { test: "throws if the recommended rows do not sum to 365000", area: "Budget · reconcile to $365K + column identities (invariants #1, #2)", file: "budget.test.ts", kind: "pure" },
      { test: "holds remaining = planned - actual and available = planned - committed row-wise + at total", area: "Budget · reconcile to $365K + column identities (invariants #1, #2)", file: "budget.test.ts", kind: "pure" },
      { test: "derives committed/actual from the ledger exactly equal to the backbone aggregates (audit immutability #6)", area: "Budget · reconcile to $365K + column identities (invariants #1, #2)", file: "budget.test.ts", kind: "pure" },
      { test: "a zero-entry workstream shows $0 actual + full remaining, not a crash (invariant #7)", area: "Budget · reconcile to $365K + column identities (invariants #1, #2)", file: "budget.test.ts", kind: "pure" },
      { test: "counts campaign spend exactly once as an origin=campaign ledger row", area: "Budget · no double-count / survivorship (invariant #3)", file: "budget.test.ts", kind: "pure" },
      { test: "rejects a campaign + matching manual entry as a double-count", area: "Budget · no double-count / survivorship (invariant #3)", file: "budget.test.ts", kind: "pure" },
      { test: "flags exactly the seeded over-plan workstream (guerrilla)", area: "Budget · variance trigger + idempotent auto-flag (invariant #4)", file: "budget.test.ts", kind: "pure" },
      { test: "respects the absolute $2,500 floor so tiny lines do not spam", area: "Budget · variance trigger + idempotent auto-flag (invariant #4)", file: "budget.test.ts", kind: "pure" },
      { test: "emits the §4 payload and is idempotent (one open flag per workstream)", area: "Budget · variance trigger + idempotent auto-flag (invariant #4)", file: "budget.test.ts", kind: "pure" },
      { test: "marks >20% over as urgent, else normal", area: "Budget · variance trigger + idempotent auto-flag (invariant #4)", file: "budget.test.ts", kind: "pure" },
      { test: "burn series is monotonic, ends at the plan total, and exposes a projected burn-out", area: "Budget · chart honesty (10b/10c)", file: "budget.test.ts", kind: "pure" },
      { test: "allocation is share-of-actual and sums to ~100%", area: "Budget · chart honesty (10b/10c)", file: "budget.test.ts", kind: "pure" },
      { test: "workstreamHealth reflects the variance thresholds", area: "Budget · chart honesty (10b/10c)", file: "budget.test.ts", kind: "pure" },
      { test: "an Operator may write only their own workstream row", area: "Budget · per-owner RBAC (invariant #5)", file: "budget.test.ts", kind: "pure" },
      { test: "a Leader can edit planned but not another owner's actual; Admin edits all", area: "Budget · per-owner RBAC (invariant #5)", file: "budget.test.ts", kind: "pure" },
      { test: "10a visibly reconciles the four workstreams to $365,000", area: "Budget · rendered sub-views (demo signal: reconcile to the total)", file: "budget.test.ts", kind: "pure" },
      { test: "does not show the HubSpot data-confidence banner on the manual Hub-owned Budget module", area: "Budget · rendered sub-views (demo signal: reconcile to the total)", file: "budget.test.ts", kind: "pure" },
      { test: "shows the viewer's own row editable and others read-only (Operator)", area: "Budget · rendered sub-views (demo signal: reconcile to the total)", file: "budget.test.ts", kind: "pure" },
      { test: "renders burn, spend, and variance sub-views", area: "Budget · rendered sub-views (demo signal: reconcile to the total)", file: "budget.test.ts", kind: "pure" },
      { test: "denies an Operator writing another owner's row (403, server-side)", area: "Budget · write route server-side RBAC", file: "budget.test.ts", kind: "pure" },
      { test: "allows an Operator to write their own row", area: "Budget · write route server-side RBAC", file: "budget.test.ts", kind: "pure" },
      { test: "allows Admin to write any row and validates the payload", area: "Budget · write route server-side RBAC", file: "budget.test.ts", kind: "pure" },
      { test: "401s an unauthenticated write before any RBAC check", area: "Budget · write route server-side RBAC", file: "budget.test.ts", kind: "pure" },
      { test: "GET reflects the caller's writable workstreams", area: "Budget · write route server-side RBAC", file: "budget.test.ts", kind: "pure" },
      { test: "builds role-aware starter layouts with stable order", area: "Home layout helpers", file: "home-layout.test.ts", kind: "pure" },
      { test: "adds, removes, and reorders widgets without duplicate keys", area: "Home layout helpers", file: "home-layout.test.ts", kind: "pure" },
      { test: "keeps saved empty layouts distinct from missing rows", area: "Home layout helpers", file: "home-layout.test.ts", kind: "pure" },
      { test: "normalizes saved shapes and tolerates unknown widget keys", area: "Home layout helpers", file: "home-layout.test.ts", kind: "pure" },
      { test: "returns the signed-in user's saved layout only", area: "GET /api/home/layout", file: "home-layout.test.ts", kind: "pure" },
      { test: "falls back to a starter layout when no row exists", area: "GET /api/home/layout", file: "home-layout.test.ts", kind: "pure" },
      { test: "ignores spoofed user ids and upserts only the signed-in user's layout", area: "PUT /api/home/layout", file: "home-layout.test.ts", kind: "pure" },
      { test: "can save an intentionally empty layout", area: "PUT /api/home/layout", file: "home-layout.test.ts", kind: "pure" },
      { test: "accepts the Home Add Widget Done payload and persists the selected layout", area: "PUT /api/home/layout", file: "home-layout.test.ts", kind: "pure" },
      { test: "returns 401 before DB access when unauthenticated", area: "PUT /api/home/layout", file: "home-layout.test.ts", kind: "pure" },
      { test: "applies field-directional authority, advances the cursor, and is STABLE across two runs", area: "reconcile sweep (live HubSpot → app)", file: "reconcile.test.ts", kind: "live" },
      { test: "#2 propagates a succeeded PI into the CORRECT program; flips paid; enqueues outbox", area: "Stripe payment propagation (live Stripe TEST sig + live Supabase)", file: "payments.test.ts", kind: "live" },
      { test: "#3 is idempotent on replay of the SAME signed event", area: "Stripe payment propagation (live Stripe TEST sig + live Supabase)", file: "payments.test.ts", kind: "live" },
      { test: "#4 out-of-order: refund (rank 3) then late succeeded (rank 2) — terminal state holds", area: "Stripe payment propagation (live Stripe TEST sig + live Supabase)", file: "payments.test.ts", kind: "live" },
      { test: "#5 cross-program write is denied by RLS (WITH CHECK)", area: "Stripe payment propagation (live Stripe TEST sig + live Supabase)", file: "payments.test.ts", kind: "live" },
      { test: "#6 rejects a tampered body / bad signature", area: "Stripe payment propagation (live Stripe TEST sig + live Supabase)", file: "payments.test.ts", kind: "live" },
      { test: "verifies a correctly-signed v3 request and rejects tamper/expiry/missing", area: "inbound HubSpot webhook (X-HubSpot-Signature-v3 + field-directional apply)", file: "hubspot-webhook.test.ts", kind: "live" },
      { test: "fails CLOSED (503 pending) when HUBSPOT_APP_SECRET is empty", area: "inbound HubSpot webhook (X-HubSpot-Signature-v3 + field-directional apply)", file: "hubspot-webhook.test.ts", kind: "live" },
      { test: "applies events through the SAME field-directional authority as reconcile, idempotently", area: "inbound HubSpot webhook (X-HubSpot-Signature-v3 + field-directional apply)", file: "hubspot-webhook.test.ts", kind: "live" },
      { test: "POST route: 200 on a correctly-signed request, 401 on a tampered body", area: "inbound HubSpot webhook (X-HubSpot-Signature-v3 + field-directional apply)", file: "hubspot-webhook.test.ts", kind: "live" },
      { test: "dispatches a real patch_deal to HubSpot and marks the row done (pending→done)", area: "outbox worker (live Supabase + live HubSpot)", file: "outbox-worker.test.ts", kind: "live" },
      { test: "two concurrent drains over the same batch dispatch each row at most once (SKIP LOCKED)", area: "outbox worker (live Supabase + live HubSpot)", file: "outbox-worker.test.ts", kind: "live" },
      { test: "backs off a retryable (429) failure and leaves the row pending with a future next_attempt_at", area: "outbox worker (live Supabase + live HubSpot)", file: "outbox-worker.test.ts", kind: "live" },
      { test: "marks a row dead after maxAttempts and auto-files a data_quality_issue", area: "outbox worker (live Supabase + live HubSpot)", file: "outbox-worker.test.ts", kind: "live" },
      { test: "non-retryable client error (4xx) goes straight to dead", area: "outbox worker (live Supabase + live HubSpot)", file: "outbox-worker.test.ts", kind: "live" },
      { test: "normalizeValue folds case/whitespace and empties to null", area: "parity engine (live seeded Supabase)", file: "parity.test.ts", kind: "live" },
      { test: "rolls up parity over governed fields: overall healthy, income below threshold; writes a snapshot", area: "parity engine (live seeded Supabase)", file: "parity.test.ts", kind: "live" },
      { test: "getBannerState names income below threshold and does NOT raise a surprise alarm", area: "parity engine (live seeded Supabase)", file: "parity.test.ts", kind: "live" },
      { test: "scopes reads to one program and fails closed when unscoped", area: "R1 — app_rw program-isolation connection smoke test", file: "r1-connection.test.ts", kind: "live" },
    ],
  },
  {
    id: "security",
    label: "Security & Access",
    domain: "AuthN/AuthZ, route policy, RBAC, program isolation & rate limiting",
    script: "npm run test:backend",
    rows: [
      { test: "requires authentication for any non-public route (401 → /login)", area: "route policy — deny by default", file: "rbac.test.ts", kind: "pure" },
      { test: "allows only the explicit public paths without a session", area: "route policy — deny by default", file: "rbac.test.ts", kind: "pure" },
      { test: "exposes the GT Challenge public capture funnel without a session", area: "route policy — deny by default", file: "rbac.test.ts", kind: "pure" },
      { test: "lets an authenticated operator into a normal module", area: "route policy — deny by default", file: "rbac.test.ts", kind: "pure" },
      { test: "denies an Operator the Decision Queue page and API with 403", area: "Decision Queue — Leadership-exclusive (view + act)", file: "rbac.test.ts", kind: "pure" },
      { test: "allows the Leader and denies Admin (exclusive to Leadership)", area: "Decision Queue — Leadership-exclusive (view + act)", file: "rbac.test.ts", kind: "pure" },
      { test: "classifies /dev and /opendata (and their APIs) as admin-only", area: "internal/dev surfaces — Admin only", file: "rbac.test.ts", kind: "pure" },
      { test: "/dev requires auth (401 unauthenticated) and is forbidden to non-admins (403)", area: "internal/dev surfaces — Admin only", file: "rbac.test.ts", kind: "pure" },
      { test: "allows Leader/Admin decision enrichment while denying Operators", area: "internal/dev surfaces — Admin only", file: "rbac.test.ts", kind: "pure" },
      { test: "classifies Ask-the-Hub as authenticated, role-aware, read-only assistance", area: "internal/dev surfaces — Admin only", file: "rbac.test.ts", kind: "pure" },
      { test: "scopes operators to their allowed program and leadership to both", area: "program scope derives from session, never the client", file: "rbac.test.ts", kind: "pure" },
      { test: "rejects a forged/out-of-scope program id (IDOR/BOLA guard)", area: "program scope derives from session, never the client", file: "rbac.test.ts", kind: "pure" },
      { test: "round-trips a signed token back to its user id", area: "session token integrity", file: "rbac.test.ts", kind: "pure" },
      { test: "rejects a tampered or malformed token", area: "session token integrity", file: "rbac.test.ts", kind: "pure" },
      { test: "rejects expired or future-dated signed tokens", area: "session token integrity", file: "rbac.test.ts", kind: "pure" },
      { test: "redirects an unauthenticated page request to /login", area: "middleware enforces the policy end-to-end", file: "rbac.test.ts", kind: "pure" },
      { test: "returns 403 JSON when an Operator hits the Decision Queue API", area: "middleware enforces the policy end-to-end", file: "rbac.test.ts", kind: "pure" },
      { test: "redirects an Operator away from the Decision Queue page", area: "middleware enforces the policy end-to-end", file: "rbac.test.ts", kind: "pure" },
      { test: "returns 401 JSON for an unauthenticated API request", area: "middleware enforces the policy end-to-end", file: "rbac.test.ts", kind: "pure" },
      { test: "lets a Leader through to the Decision Queue API", area: "middleware enforces the policy end-to-end", file: "rbac.test.ts", kind: "pure" },
      { test: "lets a Leader through to the Decision Queue page", area: "middleware enforces the policy end-to-end", file: "rbac.test.ts", kind: "pure" },
      { test: "lets the Admin into /dev", area: "middleware enforces the policy end-to-end", file: "rbac.test.ts", kind: "pure" },
      { test: "allows up to the limit, then denies with a retry-after", area: "RateLimiter — fixed window", file: "ratelimit.test.ts", kind: "pure" },
      { test: "isolates buckets per client key", area: "RateLimiter — fixed window", file: "ratelimit.test.ts", kind: "pure" },
      { test: "resets the window once it elapses", area: "RateLimiter — fixed window", file: "ratelimit.test.ts", kind: "pure" },
      { test: "rejects invalid configuration", area: "RateLimiter — fixed window", file: "ratelimit.test.ts", kind: "pure" },
      { test: "uses the left-most x-forwarded-for hop", area: "clientKeyFromRequest", file: "ratelimit.test.ts", kind: "pure" },
      { test: "falls back to x-real-ip then a shared closed bucket", area: "clientKeyFromRequest", file: "ratelimit.test.ts", kind: "pure" },
      { test: "throttles a flood from one client with 429 + Retry-After", area: "POST /api/gifted-quiz — rate limited", file: "ratelimit.test.ts", kind: "pure" },
      { test: "does not penalize a separate client", area: "POST /api/gifted-quiz — rate limited", file: "ratelimit.test.ts", kind: "pure" },
    ],
  },
  {
    id: "scenarios",
    label: "Scenarios & Use-cases",
    domain: "Brief use cases and cross-cutting product contracts made runnable",
    script: "npm run test:scenarios",
    rows: [
      { test: "UC-P1-ISOLATION: no payment references an enrollment in another program", area: "Phase 1 · backbone (data-level proofs)", file: "brief-usecases.test.ts", kind: "pure" },
      { test: "UC-P1-PAYMENT-IDEM: a twice-delivered event is recorded once in the ledger", area: "Phase 1 · backbone (data-level proofs)", file: "brief-usecases.test.ts", kind: "pure" },
      { test: "UC-P1-PAYMENT-RETRY: a failed payment is followed by a succeeded retry on the same enrollment", area: "Phase 1 · backbone (data-level proofs)", file: "brief-usecases.test.ts", kind: "pure" },
      { test: "UC-P1-DUP-WEBHOOK: a duplicated source event id survives in the log but processes at most once", area: "Phase 1 · backbone (data-level proofs)", file: "brief-usecases.test.ts", kind: "pure" },
      { test: "UC-P1-CONFLICT: an app-authoritative field records HubSpot's disagreement without overwriting local", area: "Phase 1 · backbone (data-level proofs)", file: "brief-usecases.test.ts", kind: "pure" },
      { test: "UC-P1-PARITY-SIGNAL: parity is computed below 100% and data-quality issues exist", area: "Phase 1 · backbone (data-level proofs)", file: "brief-usecases.test.ts", kind: "pure" },
      { test: "UC-P1-RECON-SUMMER: summer.gt.school + form overlap on match_key and reconcile to unique families", area: "Phase 1 · backbone (data-level proofs)", file: "brief-usecases.test.ts", kind: "pure" },
      { test: "UC-P1-RECON-AMBASSADOR: HubSpot + community ambassadors resolve to one person by match_key", area: "Phase 1 · backbone (data-level proofs)", file: "brief-usecases.test.ts", kind: "pure" },
      { test: "UC-DATA-DETERMINISM: same seed → byte-identical; different seed → different", area: "Test data deliverable", file: "brief-usecases.test.ts", kind: "pure" },
      { test: "UC-DATA-EDGECASES: all 15 deliberate edge cases are present", area: "Test data deliverable", file: "brief-usecases.test.ts", kind: "pure" },
      { test: "UC-DATA-MESSY: a mojibake name and missing-field families are present", area: "Test data deliverable", file: "brief-usecases.test.ts", kind: "pure" },
      { test: "UC-DATA-HONEST: every stood-in record is labeled real-vs-stood-in", area: "Test data deliverable", file: "brief-usecases.test.ts", kind: "pure" },
      { test: "UC-DATA-BUDGET-365: workstream recommended amounts sum to exactly $365,000", area: "Test data deliverable", file: "brief-usecases.test.ts", kind: "pure" },
      { test: "UC-DATA-VARIANCE: a >10% over-plan workstream exists and an auto-flag decision was raised", area: "Test data deliverable", file: "brief-usecases.test.ts", kind: "pure" },
      { test: "UC-DATA-ATTR-GAP: Meta over-reports leads vs CRM (modeled attribution gap)", area: "Test data deliverable", file: "brief-usecases.test.ts", kind: "pure" },
      { test: "UC-DATA-UTM-THREAD: a campaign threads CRM → Meta → GA4", area: "Test data deliverable", file: "brief-usecases.test.ts", kind: "pure" },
      { test: "UC-P2-SSOT: an app-authoritative field keeps its local value when HubSpot disagrees", area: "Phase 2 · product (data-level proofs)", file: "brief-usecases.test.ts", kind: "pure" },
      { test: "UC-P2-CRMOPS-GAPS: data-quality issues are generated for CRM Ops to surface", area: "Phase 2 · product (data-level proofs)", file: "brief-usecases.test.ts", kind: "pure" },
      { test: "UC-P2-HOME: the Home widget library has the starter pack and role-aware additions", area: "Phase 2 · product (data-level proofs)", file: "brief-usecases.test.ts", kind: "pure" },
      { test: "UC-P2-HOME-PERSISTENCE: Home add/remove/reorder layout survives as a user row", area: "Phase 2 · product (data-level proofs)", file: "brief-usecases.test.ts", kind: "pure" },
      { test: "UC-GTC-CAPTURE-ASSESS: Challenge assessment requires consent, scores, routes, and de-identifies", area: "Phase 2 · product (data-level proofs)", file: "brief-usecases.test.ts", kind: "pure" },
      { test: "UC-GTC-CAMPAIGN: the gifted-quiz campaign threads across Meta and CRM source", area: "Phase 2 · product (data-level proofs)", file: "brief-usecases.test.ts", kind: "pure" },
      { test: "UC-GTC-CAPTURE-PERSIST: public capture persists once per idempotency key with UTM and score", area: "Phase 2 · product (data-level proofs)", file: "brief-usecases.test.ts", kind: "pure" },
      { test: "UC-P2-AUTH-ROLES: auth is required and Admin/Leader/Operator are enforced at the app layer", area: "Phase 2 · product (data-level proofs)", file: "brief-usecases.test.ts", kind: "pure" },
      { test: "UC-DEMO-BUDGET: Budget Tracker logic reconciles to $365K and raises variance decisions", area: "Demo signals supported by Phase 2 helpers", file: "brief-usecases.test.ts", kind: "pure" },
      { test: "UC-DEMO-ROLE-DENIED: non-leaders are denied full Decision Queue data", area: "Demo signals supported by Phase 2 helpers", file: "brief-usecases.test.ts", kind: "pure" },
      { test: "UC-DEMO-ROLE-DENIED-AUTH-UI: Operator is denied the Decision Queue route and ruling UI", area: "Demo signals supported by Phase 2 helpers", file: "brief-usecases.test.ts", kind: "pure" },
      { test: "UC-DEMO-BANNER: data-confidence banner payload appears when parity drops", area: "Demo signals supported by Phase 2 helpers", file: "brief-usecases.test.ts", kind: "pure" },
      { test: "UC-SPEC-BUDGET-WORKSTREAMS: pre-loaded workstreams match the spec's $365K table", area: "Marketing Hub spec (data-level proofs)", file: "brief-usecases.test.ts", kind: "pure" },
      { test: "UC-SPEC-CAMP-PL: summer camp is a separate P&L, not a budget workstream", area: "Marketing Hub spec (data-level proofs)", file: "brief-usecases.test.ts", kind: "pure" },
      { test: "UC-SPEC-FIELD-RELIABILITY: exactly TEFA/income/source are unreliable, and they drift", area: "Marketing Hub spec (data-level proofs)", file: "brief-usecases.test.ts", kind: "pure" },
      { test: "UC-SPEC-SCORE-CONVERSION: top-quartile lead scores convert better than bottom-quartile", area: "Marketing Hub spec (data-level proofs)", file: "brief-usecases.test.ts", kind: "pure" },
      { test: "UC-SPEC-DQ-AUTODETECT: the data-quality queue includes UTM + sync issues", area: "Marketing Hub spec (data-level proofs)", file: "brief-usecases.test.ts", kind: "pure" },
      { test: "UC-SPEC-OUTBOX-DLQ: the sync outbox models pending, done, and dead states", area: "Marketing Hub spec (data-level proofs)", file: "brief-usecases.test.ts", kind: "pure" },
      { test: "UC-SPEC-CONTENT-PIPELINE: the content sheet spans multiple stages and reaches published", area: "Marketing Hub spec (data-level proofs)", file: "brief-usecases.test.ts", kind: "pure" },
      { test: "UC-SPEC-XLINK-TESTIMONIAL: Grassroots testimonial creates a Content idea stub", area: "Marketing Hub spec (data-level proofs)", file: "brief-usecases.test.ts", kind: "pure" },
      { test: "UC-SPEC-XLINK-OBJECTION: high-frequency Admissions objection creates a content brief", area: "Marketing Hub spec (data-level proofs)", file: "brief-usecases.test.ts", kind: "pure" },
      { test: "UC-SPEC-XLINK-HOTFAMILY: hot-family signal chips into Admissions and Decision Queue", area: "Marketing Hub spec (data-level proofs)", file: "brief-usecases.test.ts", kind: "pure" },
      { test: "UC-SPEC-XLINK-EVENT: parent-led Grassroots event maps to read-only Field Marketing", area: "Marketing Hub spec (data-level proofs)", file: "brief-usecases.test.ts", kind: "pure" },
      { test: "UC-SPEC-MONDAY-MEETING: the shared scorecard uses canonical sourced metrics", area: "Marketing Hub spec (data-level proofs)", file: "brief-usecases.test.ts", kind: "pure" },
      { test: "UC-SPEC-HANDOFF: handoff count, rate, and velocity derive from deal/payment facts", area: "Marketing Hub spec (data-level proofs)", file: "brief-usecases.test.ts", kind: "pure" },
      { test: "every use case is well-formed (id, reqs, proves, tests)", area: "Use-case catalog integrity (lib/dev/usecases.ts)", file: "brief-usecases.test.ts", kind: "pure" },
      { test: "use-case ids are unique", area: "Use-case catalog integrity (lib/dev/usecases.ts)", file: "brief-usecases.test.ts", kind: "pure" },
      { test: "every P0 hard requirement is referenced by at least one use case (traceability)", area: "Use-case catalog integrity (lib/dev/usecases.ts)", file: "brief-usecases.test.ts", kind: "pure" },
      { test: "catalog stays in sync with this file's implemented + todo cases", area: "Use-case catalog integrity (lib/dev/usecases.ts)", file: "brief-usecases.test.ts", kind: "pure" },
      { test: "exposes the E1 watcher signals from deterministic seed facts", area: "Payment propagation watcher surface contract", file: "payment-propagation-surface.test.ts", kind: "pure" },
      { test: "makes replay idempotency visible as one ledger row and one payment row", area: "Payment propagation watcher surface contract", file: "payment-propagation-surface.test.ts", kind: "pure" },
      { test: "keeps no-contamination evidence visible even when families span programs", area: "Payment propagation watcher surface contract", file: "payment-propagation-surface.test.ts", kind: "pure" },
      { test: "flags contamination instead of hiding a dirty cross-program payment", area: "Payment propagation watcher surface contract", file: "payment-propagation-surface.test.ts", kind: "pure" },
      { test: "uses a deterministic grader with no negative verdict bucket", area: "GT Challenge capture persistence model", file: "gt-challenge.test.ts", kind: "pure" },
      { test: "requires consent before anything is persisted", area: "GT Challenge capture persistence model", file: "gt-challenge.test.ts", kind: "pure" },
      { test: "collapses duplicate idempotency keys to one submission and one lead", area: "GT Challenge capture persistence model", file: "gt-challenge.test.ts", kind: "pure" },
      { test: "persists UTM, score, qualified flag, and fit bucket", area: "GT Challenge capture persistence model", file: "gt-challenge.test.ts", kind: "pure" },
      { test: "rejects non-consented submissions before persistence", area: "POST /api/gifted-quiz route contract", file: "gt-challenge.test.ts", kind: "pure" },
      { test: "returns one public submission/lead for duplicate idempotency keys", area: "POST /api/gifted-quiz route contract", file: "gt-challenge.test.ts", kind: "pure" },
      { test: "enforces Leader-only full Decision Queue access while allowing all roles to submit", area: "Phase 2 roles and Decision Queue gate", file: "phase2.test.ts", kind: "pure" },
      { test: "lets an operator edit only their owned workstream budget row", area: "Phase 2 roles and Decision Queue gate", file: "phase2.test.ts", kind: "pure" },
      { test: "hides the full queue from operators", area: "Phase 2 roles and Decision Queue gate", file: "phase2.test.ts", kind: "pure" },
      { test: "contains the PRD's 30+ widgets across the specified categories", area: "Phase 2 Home widget library", file: "phase2.test.ts", kind: "pure" },
      { test: "pre-checks the PRD starter pack and personalizes leader/operator additions", area: "Phase 2 Home widget library", file: "phase2.test.ts", kind: "pure" },
      { test: "reconciles every budget total to the PRD's $365K system of record", area: "Phase 2 Budget Tracker", file: "phase2.test.ts", kind: "pure" },
      { test: "auto-flags any workstream more than 10% over plan into Decision Queue", area: "Phase 2 Budget Tracker", file: "phase2.test.ts", kind: "pure" },
      { test: "names field-specific parity issues and points to CRM Ops", area: "Phase 2 CRM Ops and data-confidence banner", file: "phase2.test.ts", kind: "pure" },
      { test: "requires consent before a child assessment lead can be stored", area: "GT Challenge workflow", file: "phase2.test.ts", kind: "pure" },
      { test: "scores, buckets, routes, and de-identifies a qualified Challenge lead", area: "GT Challenge workflow", file: "phase2.test.ts", kind: "pure" },
      { test: "closes the Challenge campaign loop with spend, qualified leads, and CPQL caveat", area: "GT Challenge workflow", file: "phase2.test.ts", kind: "pure" },
      { test: "turns a Grassroots testimonial into a Content production stub", area: "Spec auto-cross-links and meeting workflow", file: "phase2.test.ts", kind: "pure" },
      { test: "turns a top Admissions objection into a high-urgency content brief", area: "Spec auto-cross-links and meeting workflow", file: "phase2.test.ts", kind: "pure" },
      { test: "pushes hot-family flags into the Decision Queue", area: "Spec auto-cross-links and meeting workflow", file: "phase2.test.ts", kind: "pure" },
      { test: "shows parent-led Grassroots events as read-only in Field Marketing", area: "Spec auto-cross-links and meeting workflow", file: "phase2.test.ts", kind: "pure" },
      { test: "builds the shared weekly scorecard from canonical sources", area: "Spec auto-cross-links and meeting workflow", file: "phase2.test.ts", kind: "pure" },
      { test: "summarizes marketing-to-onboarding handoff from deal/payment facts", area: "Spec auto-cross-links and meeting workflow", file: "phase2.test.ts", kind: "pure" },
      { test: "does not claim full completion while Auth, Ask-the-Hub, and Home UI controls remain partial", area: "Phase 2 requirements audit stays honest", file: "phase2.test.ts", kind: "pure" },
    ],
  },
  {
    id: "frontend",
    label: "Frontend & Routes",
    domain: "Server-rendered module surfaces, route lenses & UI state",
    script: "npm run test:frontend",
    rows: [
      { test: "Home renders the PRD top-level signals and links to the deep module slice", area: "Phase 2 rendered route surfaces", file: "module-routes.test.ts", kind: "pure" },
      { test: "Home widgets consume the selected reporting week for KPI-backed values", area: "Phase 2 rendered route surfaces", file: "module-routes.test.ts", kind: "pure" },
      { test: "dev header role switcher exposes one target per permission role", area: "Phase 2 rendered route surfaces", file: "module-routes.test.ts", kind: "pure" },
      { test: "Budget route visibly reconciles workstreams to the $365K total and variance queue", area: "Phase 2 rendered route surfaces", file: "module-routes.test.ts", kind: "pure" },
      { test: "data-confidence banner renders on HubSpot-consuming module routes", area: "Phase 2 rendered route surfaces", file: "module-routes.test.ts", kind: "pure" },
      { test: "operator role lens shows a denied Decision Queue state without queue actions", area: "Phase 2 rendered route surfaces", file: "module-routes.test.ts", kind: "pure" },
      { test: "leader role lens shows Decision Queue ruling controls", area: "Phase 2 rendered route surfaces", file: "module-routes.test.ts", kind: "pure" },
      { test: "searches the widget library by label, category, and source", area: "Home widget picker state", file: "home-widget-picker.test.ts", kind: "pure" },
      { test: "adds and removes widgets from the selected layout without duplicating keys", area: "Home widget picker state", file: "home-widget-picker.test.ts", kind: "pure" },
      { test: "reorders selected widgets and clamps boundary moves", area: "Home widget picker state", file: "home-widget-picker.test.ts", kind: "pure" },
      { test: "builds the Done payload in the Home layout API shape", area: "Home widget picker state", file: "home-widget-picker.test.ts", kind: "pure" },
      { test: "scorecard value == registry value == an independent recompute, to the digit", area: "Dashboard · single KPI definition / no drift (invariant #1)", file: "dashboard.test.ts", kind: "pure" },
      { test: "every KPI in the scorecard is defined exactly once in the registry", area: "Dashboard · single KPI definition / no drift (invariant #1)", file: "dashboard.test.ts", kind: "pure" },
      { test: "weekIndexOf is window-bounded and Monday-keyed", area: "Dashboard · single KPI definition / no drift (invariant #1)", file: "dashboard.test.ts", kind: "pure" },
      { test: "building the scorecard does not mutate the dataset", area: "Dashboard · read-only aggregator + versioned immutability (invariants #2, #3)", file: "dashboard.test.ts", kind: "pure" },
      { test: "re-building a closed week is byte-identical (deterministic snapshot)", area: "Dashboard · read-only aggregator + versioned immutability (invariants #2, #3)", file: "dashboard.test.ts", kind: "pure" },
      { test: "different weeks produce different frozen rows", area: "Dashboard · read-only aggregator + versioned immutability (invariants #2, #3)", file: "dashboard.test.ts", kind: "pure" },
      { test: "only a Leader may edit a goal", area: "Dashboard · Leader-only goal RBAC (invariant #4)", file: "dashboard.test.ts", kind: "pure" },
      { test: "a Leader edit succeeds and writes an audit row", area: "Dashboard · Leader-only goal RBAC (invariant #4)", file: "dashboard.test.ts", kind: "pure" },
      { test: "an Operator or Admin edit is rejected and writes nothing", area: "Dashboard · Leader-only goal RBAC (invariant #4)", file: "dashboard.test.ts", kind: "pure" },
      { test: "uninstrumented KPIs are low-confidence; measured KPIs are not", area: "Dashboard · honesty flag + biggest-mover (invariant #5)", file: "dashboard.test.ts", kind: "pure" },
      { test: "the biggest mover is drawn only from instrumented KPIs", area: "Dashboard · honesty flag + biggest-mover (invariant #5)", file: "dashboard.test.ts", kind: "pure" },
      { test: "pacing projection carries a low-confidence flag for uninstrumented inputs", area: "Dashboard · honesty flag + biggest-mover (invariant #5)", file: "dashboard.test.ts", kind: "pure" },
      { test: "exactly one connector is stale (the seeded aged X connector)", area: "Dashboard · freshness (invariant #7)", file: "dashboard.test.ts", kind: "pure" },
      { test: "a fresh connector's age is within its SLA", area: "Dashboard · freshness (invariant #7)", file: "dashboard.test.ts", kind: "pure" },
      { test: "applicants series is per-week, length 13, and sums to the windowed applicant count", area: "Dashboard · weekly series sanity", file: "dashboard.test.ts", kind: "pure" },
      { test: "parity series tracks the seeded week-6 dip below threshold", area: "Dashboard · weekly series sanity", file: "dashboard.test.ts", kind: "pure" },
      { test: "6a scorecard renders one row per KPI with the shared-board framing", area: "Dashboard · rendered sub-views", file: "dashboard.test.ts", kind: "pure" },
      { test: "renders trends, sla, pacing, and the display-only mirror", area: "Dashboard · rendered sub-views", file: "dashboard.test.ts", kind: "pure" },
      { test: "the data-confidence banner is consumed on this HubSpot-derived board", area: "Dashboard · rendered sub-views", file: "dashboard.test.ts", kind: "pure" },
      { test: "goal editing is read-only for Admin and Operator (UI mirrors server RBAC)", area: "Dashboard · rendered sub-views", file: "dashboard.test.ts", kind: "pure" },
      { test: "allows a Leader to edit a goal", area: "Dashboard · goal-edit route server-side RBAC", file: "dashboard.test.ts", kind: "pure" },
      { test: "denies an Admin and an Operator (403, server-side)", area: "Dashboard · goal-edit route server-side RBAC", file: "dashboard.test.ts", kind: "pure" },
      { test: "validates the payload (unknown KPI / bad value) for a Leader", area: "Dashboard · goal-edit route server-side RBAC", file: "dashboard.test.ts", kind: "pure" },
      { test: "401s an unauthenticated edit before any RBAC check", area: "Dashboard · goal-edit route server-side RBAC", file: "dashboard.test.ts", kind: "pure" },
      { test: "GET reflects the caller's goal-edit capability", area: "Dashboard · goal-edit route server-side RBAC", file: "dashboard.test.ts", kind: "pure" },
      { test: "engagement fields and conversion fields are disjoint (no shared field)", area: "Nurture · SSOT + no circularity (invariants #1, #2)", file: "nurture.test.ts", kind: "pure" },
      { test: "engagement tier never reads funnel_stage (toggling funnel does not change tier)", area: "Nurture · SSOT + no circularity (invariants #1, #2)", file: "nurture.test.ts", kind: "pure" },
      { test: "tier mix sums to the population", area: "Nurture · SSOT + no circularity (invariants #1, #2)", file: "nurture.test.ts", kind: "pure" },
      { test: "every cell carries n; cells with n<25 are suppressed (no pct)", area: "Nurture · heatmap small-cell honesty (invariant #3)", file: "nurture.test.ts", kind: "pure" },
      { test: "conversion% is measured (clicked tier converts higher than cold) and bounded 0..100", area: "Nurture · heatmap small-cell honesty (invariant #3)", file: "nurture.test.ts", kind: "pure" },
      { test: "T1/T2/T3 partition the population exactly once", area: "Nurture · segments (invariant #1 SSOT)", file: "nurture.test.ts", kind: "pure" },
      { test: "T3 buckets read tefa_status (app_form) and sum to the waitlist size", area: "Nurture · segments (invariant #1 SSOT)", file: "nurture.test.ts", kind: "pure" },
      { test: "each fall deal appears once in the parent distribution", area: "Nurture · pipeline reconciliation (invariant #4)", file: "nurture.test.ts", kind: "pure" },
      { test: "handoff conversion is between 0 and 1 (no double-count)", area: "Nurture · pipeline reconciliation (invariant #4)", file: "nurture.test.ts", kind: "pure" },
      { test: "SLA% = contacted_within_24h ÷ new_applicants", area: "Nurture · SLA correctness (invariant #6)", file: "nurture.test.ts", kind: "pure" },
      { test: "every late-list row is owner-attributable (non-null owner) and uncontacted", area: "Nurture · SLA correctness (invariant #6)", file: "nurture.test.ts", kind: "pure" },
      { test: "is deterministic across runs", area: "Nurture · SLA correctness (invariant #6)", file: "nurture.test.ts", kind: "pure" },
      { test: "v1 keyword rules classify tuition / scheduling and fall back to untagged", area: "Nurture · SMS theming + consent (invariants #7, #8)", file: "nurture.test.ts", kind: "pure" },
      { test: "every thread carries at least one theme", area: "Nurture · SMS theming + consent (invariants #7, #8)", file: "nurture.test.ts", kind: "pure" },
      { test: "an opted-out thread cannot be quick-replied", area: "Nurture · SMS theming + consent (invariants #7, #8)", file: "nurture.test.ts", kind: "pure" },
      { test: "objection filter returns tuition threads", area: "Nurture · SMS theming + consent (invariants #7, #8)", file: "nurture.test.ts", kind: "pure" },
      { test: "SMS PII gated to Admin/Leader; Operator masked", area: "Nurture · RBAC + PII (invariants #8, #11)", file: "nurture.test.ts", kind: "pure" },
      { test: "only Leaders may act on a hot-family decision", area: "Nurture · RBAC + PII (invariants #8, #11)", file: "nurture.test.ts", kind: "pure" },
      { test: "flagging the same family twice yields exactly one flag", area: "Nurture · cross-link idempotency (invariant #9)", file: "nurture.test.ts", kind: "pure" },
      { test: "flags an unhealthy sequence and produces exactly one decision payload", area: "Nurture · sequences read-only (invariant #5)", file: "nurture.test.ts", kind: "pure" },
      { test: "overview + segments + heatmap render", area: "Nurture · rendered sub-views", file: "nurture.test.ts", kind: "pure" },
      { test: "SMS inbox masks PII for an Operator and shows it for Admin", area: "Nurture · rendered sub-views", file: "nurture.test.ts", kind: "pure" },
      { test: "renders pipeline, sequences, and SLA tabs", area: "Nurture · rendered sub-views", file: "nurture.test.ts", kind: "pure" },
      { test: "collapses a match_key present in both feeds to exactly one golden row", area: "Grassroots · dual-source reconcile (invariants #1, #2, #3)", file: "grassroots.test.ts", kind: "pure" },
      { test: "survivorship picks the most-advanced stage on conflict and logs the loss", area: "Grassroots · dual-source reconcile (invariants #1, #2, #3)", file: "grassroots.test.ts", kind: "pure" },
      { test: "no ambassador is dropped; every golden row is in exactly one of the 5 stages", area: "Grassroots · dual-source reconcile (invariants #1, #2, #3)", file: "grassroots.test.ts", kind: "pure" },
      { test: "influenced enrollments read app_form referral attribution (not a constant)", area: "Grassroots · metrics single-definition (invariants #4, #5, #6)", file: "grassroots.test.ts", kind: "pure" },
      { test: "intros/P2P are the de-duplicated activity sum (2a == 2b)", area: "Grassroots · metrics single-definition (invariants #4, #5, #6)", file: "grassroots.test.ts", kind: "pure" },
      { test: "active count includes only Active/Champion stages", area: "Grassroots · metrics single-definition (invariants #4, #5, #6)", file: "grassroots.test.ts", kind: "pure" },
      { test: "pipeline stage counts sum to the roster total", area: "Grassroots · metrics single-definition (invariants #4, #5, #6)", file: "grassroots.test.ts", kind: "pure" },
      { test: "each category has coverage% = contacted/total, bounded 0..100, ungeocoded explicit", area: "Grassroots · market coverage denominator (invariant #7)", file: "grassroots.test.ts", kind: "pure" },
      { test: "logging a testimonial twice creates exactly one Content stub", area: "Grassroots · cross-links idempotent + minimized (invariants #9, #10, #11)", file: "grassroots.test.ts", kind: "pure" },
      { test: "a hot-family flag carries minimized PII only", area: "Grassroots · cross-links idempotent + minimized (invariants #9, #10, #11)", file: "grassroots.test.ts", kind: "pure" },
      { test: "parent-event cross-link to Field Marketing is read-only", area: "Grassroots · cross-links idempotent + minimized (invariants #9, #10, #11)", file: "grassroots.test.ts", kind: "pure" },
      { test: "overview goal bars + roster reconcile render", area: "Grassroots · rendered sub-views", file: "grassroots.test.ts", kind: "pure" },
      { test: "Operator sees submit-not-view Decision Queue framing", area: "Grassroots · rendered sub-views", file: "grassroots.test.ts", kind: "pure" },
      { test: "renders market map, sprints, community, events", area: "Grassroots · rendered sub-views", file: "grassroots.test.ts", kind: "pure" },
      { test: "the verbatim 'is my kid gifted enough' maps to gifted_enough, never other", area: "Admissions · theme closure (invariant #2)", file: "admissions.test.ts", kind: "pure" },
      { test: "every objection theme is in the closed 8-theme set", area: "Admissions · theme closure (invariant #2)", file: "admissions.test.ts", kind: "pure" },
      { test: "a re-surfaced thread (same source_ref+theme) does not inflate frequency", area: "Admissions · dedup (invariant #1)", file: "admissions.test.ts", kind: "pure" },
      { test: "a multi-objection thread keeps distinct themes from the same source_ref", area: "Admissions · dedup (invariant #1)", file: "admissions.test.ts", kind: "pure" },
      { test: "pipeline numbers equal counts derived from families.funnel_stage", area: "Admissions · pipeline SSOT (invariant #3)", file: "admissions.test.ts", kind: "pure" },
      { test: "stubbing the same theme twice yields one open brief", area: "Admissions · bridge idempotency + honesty (invariant #4)", file: "admissions.test.ts", kind: "pure" },
      { test: "bridge effect is labeled correlational with a window + delta", area: "Admissions · bridge idempotency + honesty (invariant #4)", file: "admissions.test.ts", kind: "pure" },
      { test: "hit-rate = produced ÷ sent", area: "Admissions · bridge idempotency + honesty (invariant #4)", file: "admissions.test.ts", kind: "pure" },
      { test: "no unconsented quote appears in the public feed or quote-of-week", area: "Admissions · consent gate (invariant #5)", file: "admissions.test.ts", kind: "pure" },
      { test: "closure_rate = actioned within 7d ÷ flagged (a late action does not count)", area: "Admissions · closure rate + RBAC (invariants #6, #7)", file: "admissions.test.ts", kind: "pure" },
      { test: "Operator may submit feedback but cannot view the Decision Queue", area: "Admissions · closure rate + RBAC (invariants #6, #7)", file: "admissions.test.ts", kind: "pure" },
      { test: "the trend arrow matches the sign of (this - prior) per theme", area: "Admissions · trend correctness (invariant #9)", file: "admissions.test.ts", kind: "pure" },
      { test: "overview + objection log render with trend arrows", area: "Admissions · rendered sub-views", file: "admissions.test.ts", kind: "pure" },
      { test: "voice of families hides unconsented quotes and shows quote-of-week", area: "Admissions · rendered sub-views", file: "admissions.test.ts", kind: "pure" },
      { test: "renders bridge + feedback; Operator sees submit-not-view framing", area: "Admissions · rendered sub-views", file: "admissions.test.ts", kind: "pure" },
      { test: "builds one content piece per sheet row plus explicit cross-link stubs", area: "Content · sheet mirror and production pipeline", file: "content.test.ts", kind: "pure" },
      { test: "blocks camp rows and unconsented testimonial stubs from advancing", area: "Content · sheet mirror and production pipeline", file: "content.test.ts", kind: "pure" },
      { test: "flags same-day/channel calendar conflicts", area: "Content · sheet mirror and production pipeline", file: "content.test.ts", kind: "pure" },
      { test: "joins content UTM to app_form conversions and keeps missing UTM explicit", area: "Content · attribution and channel separation", file: "content.test.ts", kind: "pure" },
      { test: "computes channel shares and the X ratio from seed data, not a constant", area: "Content · attribution and channel separation", file: "content.test.ts", kind: "pure" },
      { test: "keeps Facebook, Instagram, and X as separate performance rows", area: "Content · attribution and channel separation", file: "content.test.ts", kind: "pure" },
      { test: "brand voice suggestions never block publish", area: "Content · brand voice, cross-links, and sync conflicts", file: "content.test.ts", kind: "pure" },
      { test: "Grassroots testimonial and VoC objection ingests are idempotent", area: "Content · brand voice, cross-links, and sync conflicts", file: "content.test.ts", kind: "pure" },
      { test: "both-sides sheet/app edits become conflicts with both values retained", area: "Content · brand voice, cross-links, and sync conflicts", file: "content.test.ts", kind: "pure" },
      { test: "overview and pipeline render the source-of-truth framing", area: "Content · rendered sub-views", file: "content.test.ts", kind: "pure" },
      { test: "calendar, performance, and library tabs render their proof surfaces", area: "Content · rendered sub-views", file: "content.test.ts", kind: "pure" },
      { test: "aggregate sessions equal the sum of both GA4 properties", area: "Analytics · GA4 source-of-truth metrics", file: "analytics.test.ts", kind: "pure" },
      { test: "bounce has one bounded definition: 1 - engaged/sessions", area: "Analytics · GA4 source-of-truth metrics", file: "analytics.test.ts", kind: "pure" },
      { test: "UTM validation keeps valid, invalid, and missing buckets explicit", area: "Analytics · GA4 source-of-truth metrics", file: "analytics.test.ts", kind: "pure" },
      { test: "download rows reconcile exactly to the PDF widget total", area: "Analytics · GA4 source-of-truth metrics", file: "analytics.test.ts", kind: "pure" },
      { test: "conversion paths are explicitly stand-in and page rows are never dropped", area: "Analytics · GA4 source-of-truth metrics", file: "analytics.test.ts", kind: "pure" },
      { test: "only Admin/Leader can flag pages for analysis", area: "Analytics · RBAC", file: "analytics.test.ts", kind: "pure" },
      { test: "overview renders aggregate reconciliation and GA4 confidence framing", area: "Analytics · rendered sub-views", file: "analytics.test.ts", kind: "pure" },
      { test: "renders subpages, source validation, downloads, and path tabs", area: "Analytics · rendered sub-views", file: "analytics.test.ts", kind: "pure" },
      { test: "a child on both site + form collapses to one row with both source feeds", area: "Summer Camp · no double-count + merged feeds (invariant #1)", file: "summer-camp.test.ts", kind: "pure" },
      { test: "re-running reconcile yields the same resolved_key set, no new rows", area: "Summer Camp · reconcile is idempotent (invariant #2)", file: "summer-camp.test.ts", kind: "pure" },
      { test: "a weeks disagreement keeps the site value AND raises a conflict", area: "Summer Camp · conflict surfaced, not averaged (invariant #3)", file: "summer-camp.test.ts", kind: "pure" },
      { test: "the 4 campuses show distinct capacities; aggregate is a sum, not an average", area: "Summer Camp · real per-campus capacity (invariant #4)", file: "summer-camp.test.ts", kind: "pure" },
      { test: "cash revenue = Σ succeeded camp payments; per-family divides by distinct families", area: "Summer Camp · measured revenue (invariant #5)", file: "summer-camp.test.ts", kind: "pure" },
      { test: "the marketing budget total stays $365,000 regardless of camp activity", area: "Summer Camp · P&L isolation (invariant #6)", file: "summer-camp.test.ts", kind: "pure" },
      { test: "a non-camp Operator is denied the roster; camp Operator/Leader/Admin allowed", area: "Summer Camp · RBAC + minors gate (invariant #8)", file: "summer-camp.test.ts", kind: "pure" },
      { test: "only Leader sets the target / views the Decision Queue", area: "Summer Camp · RBAC + minors gate (invariant #8)", file: "summer-camp.test.ts", kind: "pure" },
      { test: "there is no ad-spend row and shares sum to ~100%", area: "Summer Camp · honest organic-only channels (invariant #9)", file: "summer-camp.test.ts", kind: "pure" },
      { test: "Lead ≥ Registered ≥ Paid ≥ Attended", area: "Summer Camp · funnel is cumulative", file: "summer-camp.test.ts", kind: "pure" },
      { test: "overview renders revenue vs target + P&L isolation", area: "Summer Camp · rendered sub-views", file: "summer-camp.test.ts", kind: "pure" },
      { test: "sessions roster is gated: leader sees it, plain operator does not", area: "Summer Camp · rendered sub-views", file: "summer-camp.test.ts", kind: "pure" },
      { test: "funnel + content tabs render", area: "Summer Camp · rendered sub-views", file: "summer-camp.test.ts", kind: "pure" },
      { test: "Operator proposal CTA points to own-status, not the full queue", area: "Summer Camp · rendered sub-views", file: "summer-camp.test.ts", kind: "pure" },
      { test: "every consults row is manual_entry and event→consult is flagged uninstrumented", area: "Events · honesty / uninstrumented (invariant #1)", file: "events.test.ts", kind: "pure" },
      { test: "ambassador events render distinctly and are excluded from GT-organized counts", area: "Events · read-only overlay, no double-count (invariant #2)", file: "events.test.ts", kind: "pure" },
      { test: "submitting a proposal twice creates exactly one decision row", area: "Events · decision intake idempotent + RBAC (invariants #3, #5)", file: "events.test.ts", kind: "pure" },
      { test: "the intake question + lead-time are well-formed", area: "Events · decision intake idempotent + RBAC (invariants #3, #5)", file: "events.test.ts", kind: "pure" },
      { test: "Operator submits but cannot view the Decision Queue; non-owner cannot edit", area: "Events · decision intake idempotent + RBAC (invariants #3, #5)", file: "events.test.ts", kind: "pure" },
      { test: "event spend rolls into a workstream; the plan still sums to $365K", area: "Events · budget reconcile (invariant #4)", file: "events.test.ts", kind: "pure" },
      { test: "attendance-rate = Σattendance/Σrsvp; event→consult = Σconsults/Σrsvp", area: "Events · single metric definition (invariant #6)", file: "events.test.ts", kind: "pure" },
      { test: "a duplicate (name+date) is flagged and not counted twice", area: "Events · duplicate flag + validation (invariant #7)", file: "events.test.ts", kind: "pure" },
      { test: "required fields are enforced", area: "Events · duplicate flag + validation (invariant #7)", file: "events.test.ts", kind: "pure" },
      { test: "upcoming-30d + top-type compute purely from field_events", area: "Events · widget Inputs→Outputs (invariant #8)", file: "events.test.ts", kind: "pure" },
      { test: "overview shows the uninstrumented badge", area: "Events · rendered sub-views", file: "events.test.ts", kind: "pure" },
      { test: "tracker flags duplicates; calendar shows read-only ambassador overlay", area: "Events · rendered sub-views", file: "events.test.ts", kind: "pure" },
      { test: "proposals tab denies queue view for operator", area: "Events · rendered sub-views", file: "events.test.ts", kind: "pure" },
      { test: "an Operator never receives a leadership-only resource", area: "Library · query-layer RBAC denial (invariant #1)", file: "library.test.ts", kind: "pure" },
      { test: "search cannot leak a leadership row even with a matching query", area: "Library · query-layer RBAC denial (invariant #1)", file: "library.test.ts", kind: "pure" },
      { test: "every row carries ≥1 controlled-vocab tag; tag filter returns exactly its rows", area: "Library · every resource is filed (invariant #2)", file: "library.test.ts", kind: "pure" },
      { test: "badges derive from URL/MIME, never mismatched", area: "Library · badge truth (invariant #3)", file: "library.test.ts", kind: "pure" },
      { test: "partial/synonym, case/diacritic-insensitive queries find the intended sample", area: "Library · small-n search recall (invariant #4)", file: "library.test.ts", kind: "pure" },
      { test: "a valid upload yields a row with owner=current user and date=now, badge derived", area: "Library · upload Inputs→Outputs (invariant #5)", file: "library.test.ts", kind: "pure" },
      { test: "non-PDF resources never get a download chip; PDF chip equals a read-only GA4 derivation", area: "Library · no fabricated counts (invariant #6)", file: "library.test.ts", kind: "pure" },
      { test: "with no Analytics data, no chip is fabricated", area: "Library · no fabricated counts (invariant #6)", file: "library.test.ts", kind: "pure" },
      { test: "a dead-linked resource is flagged link_ok=false", area: "Library · link health + honesty (invariants #7, #8)", file: "library.test.ts", kind: "pure" },
      { test: "every mocked resource is is_sample=true (reset to a known state)", area: "Library · link health + honesty (invariants #7, #8)", file: "library.test.ts", kind: "pure" },
      { test: "edit is allowed for owner or admin only", area: "Library · link health + honesty (invariants #7, #8)", file: "library.test.ts", kind: "pure" },
      { test: "operator shelf excludes Brand Strategy; leader shelf includes it", area: "Library · rendered shelf", file: "library.test.ts", kind: "pure" },
      { test: "search filters the shelf; dead link renders an unreachable state", area: "Library · rendered shelf", file: "library.test.ts", kind: "pure" },
      { test: "no-match renders the empty state", area: "Library · rendered shelf", file: "library.test.ts", kind: "pure" },
    ],
  },
];

export interface CatalogCounts {
  total: number;
  pure: number;
  live: number;
  groups: number;
  files: number;
}

export function catalogCounts(): CatalogCounts {
  const rows = TEST_GROUPS.flatMap((g) => g.rows);
  const files = new Set(rows.map((r) => r.file));
  return {
    total: rows.length,
    pure: rows.filter((r) => r.kind === "pure").length,
    live: rows.filter((r) => r.kind === "live").length,
    groups: TEST_GROUPS.length,
    files: files.size,
  };
}

export function groupCounts(group: TestGroup): { total: number; pure: number; live: number } {
  return {
    total: group.rows.length,
    pure: group.rows.filter((r) => r.kind === "pure").length,
    live: group.rows.filter((r) => r.kind === "live").length,
  };
}
