/**
 * Brief-derived use cases — the scenarios the Technical Project Brief asks us to
 * prove, mapped to the tests that cover them. This is the single source of truth
 * for the in-app Test Theater (/dev/tests) and the catalog-integrity meta-tests in
 * tests/brief-usecases.test.ts.
 *
 * status:
 *   covered  — has always-running assertions (pure, no services needed)
 *   live     — proven, but only runs with real services (skips gracefully pre-keys)
 *   pending  — product feature not built yet; tracked as it.todo (honest red)
 */

export type UseCasePhase =
  | "Phase 1 · Backbone"
  | "Test data"
  | "Phase 2 · Product"
  | "Spec · Marketing Hub"
  | "Demo signal";

export type UseCaseStatus = "covered" | "live" | "pending";
export type ServiceReq = "pure" | "db" | "hubspot" | "stripe" | "opendata";

export interface UseCase {
  id: string;
  title: string;
  phase: UseCasePhase;
  /** Where the brief asks for it. */
  brief: string;
  /** REQUIREMENTS.md ids this exercises. */
  reqs: string[];
  /** What a green test demonstrates. */
  proves: string;
  status: UseCaseStatus;
  requires: ServiceReq[];
  /** Test files / cases that cover it. */
  tests: string[];
}

export const UC_PHASES: UseCasePhase[] = [
  "Phase 1 · Backbone",
  "Test data",
  "Phase 2 · Product",
  "Spec · Marketing Hub",
  "Demo signal",
];

export const USE_CASES: UseCase[] = [
  // ───────────────────────── Phase 1 · Backbone ─────────────────────────
  {
    id: "UC-P1-SYNC-BIDIR",
    title: "Bidirectional CRM↔app sync, consistent over time",
    phase: "Phase 1 · Backbone",
    brief: "Phase 1 — “Sync data both directions… keep them consistent over time, not just on first import.”",
    reqs: ["B1"],
    proves: "Inbound reconcile applies HubSpot changes by field authority; outbound outbox pushes app changes; parity is stable across repeated runs (no echo oscillation).",
    status: "live",
    requires: ["db", "hubspot"],
    tests: ["reconcile.test.ts › applies field-directional authority… STABLE across two runs", "outbox-worker.test.ts", "hubspot-webhook.test.ts"],
  },
  {
    id: "UC-P1-ISOLATION",
    title: "Program isolation — no cross-program read/write",
    phase: "Phase 1 · Backbone",
    brief: "Phase 1 — “Keep each program’s data strictly isolated… Prove this.”",
    reqs: ["B2"],
    proves: "RLS denies a cross-program write (WITH CHECK); seeded payments never reference an enrollment in another program.",
    status: "covered",
    requires: ["pure", "db"],
    tests: ["brief-usecases.test.ts › UC-P1-ISOLATION", "payments.test.ts › cross-program write denied by RLS", "supabase/checks/r1_isolation.sql"],
  },
  {
    id: "UC-P1-PAYMENT-IDEM",
    title: "Idempotent payment end-to-end",
    phase: "Phase 1 · Backbone",
    brief: "Phase 1 — “Process a payment event end-to-end… Make it idempotent.”",
    reqs: ["B3", "E1"],
    proves: "A Stripe event delivered twice flips state once and is recorded once in the idempotency ledger.",
    status: "covered",
    requires: ["pure", "db", "stripe"],
    tests: ["brief-usecases.test.ts › UC-P1-PAYMENT-IDEM", "payments.test.ts › idempotent on replay of the same signed event"],
  },
  {
    id: "UC-P1-PAYMENT-RETRY",
    title: "Failed → succeeded retry, monotonic state",
    phase: "Phase 1 · Backbone",
    brief: "Phase 1 — “a late/failed/duplicate payment… no lost updates.”",
    reqs: ["B3", "B5"],
    proves: "A failed payment followed by a succeeded retry on the same enrollment ends in the terminal paid state.",
    status: "covered",
    requires: ["pure", "db", "stripe"],
    tests: ["brief-usecases.test.ts › UC-P1-PAYMENT-RETRY", "payments.test.ts › out-of-order refund→succeeded does not regress (monotonic guard)"],
  },
  {
    id: "UC-P1-DUP-WEBHOOK",
    title: "Duplicate webhook deduped",
    phase: "Phase 1 · Backbone",
    brief: "Phase 1 — “Handle the messy parts: … duplicate webhooks…”",
    reqs: ["B5"],
    proves: "A duplicated source event id appears in the event log twice but is processed at most once.",
    status: "covered",
    requires: ["pure", "db"],
    tests: ["brief-usecases.test.ts › UC-P1-DUP-WEBHOOK", "payments.test.ts"],
  },
  {
    id: "UC-P1-CONFLICT",
    title: "Conflicting CRM vs app edits resolved by authority",
    phase: "Phase 1 · Backbone",
    brief: "Phase 1 — “conflicting edits… Decide what ‘correct’ means and enforce it.”",
    reqs: ["B5", "C3"],
    proves: "For app-authoritative fields, a disagreeing HubSpot value is recorded (in_parity=false) but never overwrites the local value.",
    status: "covered",
    requires: ["pure", "db"],
    tests: ["brief-usecases.test.ts › UC-P1-CONFLICT", "reconcile.test.ts"],
  },
  {
    id: "UC-P1-PARITY-SIGNAL",
    title: "Sync-parity / data-confidence signal",
    phase: "Phase 1 · Backbone",
    brief: "Phase 1 — “Expose a sync-parity / data-confidence signal… Build the plumbing that makes that honest.”",
    reqs: ["B4", "E4"],
    proves: "Parity is computed per field and overall; conflicts pull it below 100%; data-quality issues are recorded.",
    status: "covered",
    requires: ["pure", "db"],
    tests: ["brief-usecases.test.ts › UC-P1-PARITY-SIGNAL", "parity.test.ts"],
  },
  {
    id: "UC-P1-RECON-SUMMER",
    title: "Dual-source reconcile: summer.gt.school + form, no double-count",
    phase: "Phase 1 · Backbone",
    brief: "Phase 1 — “reconciling dual sources (summer.gt.school + a registration form)… without double-counting.”",
    reqs: ["B5", "C6", "D3"],
    proves: "The two feeds overlap on match_key; reconciling by match_key collapses duplicates so a family is counted once.",
    status: "covered",
    requires: ["pure"],
    tests: ["brief-usecases.test.ts › UC-P1-RECON-SUMMER"],
  },
  {
    id: "UC-P1-RECON-AMBASSADOR",
    title: "Dual-source reconcile: HubSpot + community ambassadors",
    phase: "Phase 1 · Backbone",
    brief: "Phase 1 — “(HubSpot + community.gt.school)… the same discipline.”",
    reqs: ["B5", "C6"],
    proves: "Ambassadors present in both HubSpot and community.gt.school resolve to one person by match_key.",
    status: "covered",
    requires: ["pure"],
    tests: ["brief-usecases.test.ts › UC-P1-RECON-AMBASSADOR"],
  },

  // ───────────────────────── Test data deliverable ─────────────────────────
  {
    id: "UC-DATA-DETERMINISM",
    title: "Reproducible: same seed → byte-identical dataset",
    phase: "Test data",
    brief: "Data — “Make it reproducible and honest… reset to a clean known state.”",
    reqs: ["D4"],
    proves: "Generation is deterministic per seed and changes with the seed; resettable for the walkthrough.",
    status: "covered",
    requires: ["pure"],
    tests: ["seed.test.ts › is deterministic", "brief-usecases.test.ts › UC-DATA-DETERMINISM"],
  },
  {
    id: "UC-DATA-EDGECASES",
    title: "Deliberate edge cases present (15)",
    phase: "Test data",
    brief: "Data — “Edge cases on purpose: duplicates, a family in two programs, a late/failed/duplicate payment, conflicting CRM vs app values, a sync-parity drop, mojibake or missing fields.”",
    reqs: ["D3"],
    proves: "All 15 deliberate edge cases are generated and asserted by the invariants.",
    status: "covered",
    requires: ["pure"],
    tests: ["seed.test.ts › records all 15 deliberate edge cases", "brief-usecases.test.ts › UC-DATA-EDGECASES"],
  },
  {
    id: "UC-DATA-MESSY",
    title: "Messy data on purpose: mojibake + missing fields",
    phase: "Test data",
    brief: "Data — “Edge cases on purpose: … mojibake or missing fields.”",
    reqs: ["D3"],
    proves: "The seed includes a UTF-8 mis-decoded (mojibake) name and families with missing email/zip.",
    status: "covered",
    requires: ["pure"],
    tests: ["brief-usecases.test.ts › UC-DATA-MESSY"],
  },
  {
    id: "UC-DATA-HONEST",
    title: "Real vs stood-in labeled honestly",
    phase: "Test data",
    brief: "Data — “label clearly what is real vs. stood-in.”",
    reqs: ["D4", "C8"],
    proves: "Every stood-in record carries _standIn=true and a _source label.",
    status: "covered",
    requires: ["pure"],
    tests: ["seed.test.ts › labels every stood-in record honestly", "brief-usecases.test.ts › UC-DATA-HONEST"],
  },
  {
    id: "UC-DATA-BUDGET-365",
    title: "Budget reconciles to $365K",
    phase: "Test data",
    brief: "Brief — “the Budget Tracker where every workstream’s spend reconciles to the $365K total.”",
    reqs: ["C4", "D1"],
    proves: "Workstream recommended amounts sum to exactly 365,000.",
    status: "covered",
    requires: ["pure"],
    tests: ["seed.test.ts › models a $365K budget", "brief-usecases.test.ts › UC-DATA-BUDGET-365"],
  },
  {
    id: "UC-DATA-VARIANCE",
    title: ">10% over-plan workstream auto-flags a decision",
    phase: "Test data",
    brief: "Brief — “>10% variance auto-flags to the Decision Queue.”",
    reqs: ["C4"],
    proves: "Seed includes a workstream whose actual exceeds plan by >10% and an auto_flag decision raised by that rule.",
    status: "covered",
    requires: ["pure"],
    tests: ["brief-usecases.test.ts › UC-DATA-VARIANCE"],
  },
  {
    id: "UC-DATA-ATTR-GAP",
    title: "Attribution gap: Meta over-reports vs CRM",
    phase: "Test data",
    brief: "Spec — modeled attribution gap; brief — “UTM attribution is broken… Surface honestly.”",
    reqs: ["C8", "D3"],
    proves: "Platform-reported Meta leads exceed CRM families sourced to meta_ads (realistic over-reporting).",
    status: "covered",
    requires: ["pure"],
    tests: ["seed.test.ts › models Meta over-reporting", "brief-usecases.test.ts › UC-DATA-ATTR-GAP"],
  },
  {
    id: "UC-DATA-UTM-THREAD",
    title: "UTM threads CRM → Meta → GA4",
    phase: "Test data",
    brief: "Spec — UTM as the analytics join key across stand-ins.",
    reqs: ["C7", "D1"],
    proves: "Campaigns share a utm_campaign across families, Meta insights, and GA4 days (joinable end-to-end).",
    status: "covered",
    requires: ["pure"],
    tests: ["seed.test.ts › threads UTM campaigns", "brief-usecases.test.ts › UC-DATA-UTM-THREAD"],
  },

  // ───────────────────────── Phase 2 · Product ─────────────────────────
  {
    id: "UC-P2-SSOT",
    title: "Single source of truth per number",
    phase: "Phase 2 · Product",
    brief: "Non-negotiable — “every number traces to exactly one authoritative source… Don’t compute the same figure two ways.”",
    reqs: ["C3"],
    proves: "app_form-authoritative fields keep their local value even when HubSpot disagrees (authority direction enforced).",
    status: "covered",
    requires: ["pure", "db"],
    tests: ["brief-usecases.test.ts › UC-P2-SSOT", "reconcile.test.ts"],
  },
  {
    id: "UC-P2-CRMOPS-GAPS",
    title: "Known gaps surfaced honestly (UTM broken, unreliable fields)",
    phase: "Phase 2 · Product",
    brief: "Non-negotiable — “Respect the known gaps… Surface these honestly rather than faking green.”",
    reqs: ["C8", "B4"],
    proves: "Data-quality issues are generated (incl. UTM/sync categories) for CRM Ops to surface.",
    status: "covered",
    requires: ["pure"],
    tests: ["brief-usecases.test.ts › UC-P2-CRMOPS-GAPS", "crm-ops.test.ts › CRM Ops · auto-detector"],
  },
  {
    id: "UC-P2-OPENDATA",
    title: "Open Data query that changes a decision",
    phase: "Phase 2 · Product",
    brief: "Brief — “a real Open Data query that changes a decision.”",
    reqs: ["C7", "E5"],
    proves: "The Open Data client caches, falls back to fixtures, and enrichment yields a GT signal that can flip a recommendation.",
    status: "covered",
    requires: ["opendata", "pure"],
    tests: ["opendata.test.ts › recommendationImpactFromEnrichment", "module-routes.test.ts › Decision impact", "catalog.test.ts"],
  },
  {
    id: "UC-P2-ASK",
    title: "Ask-the-Hub gives cited, role-aware operating answers",
    phase: "Phase 2 · Product",
    brief: "Optional AI layer — “an Ask-the-Hub agent answering … across HubSpot and Open Data.”",
    reqs: ["C1", "C3", "C7", "C8"],
    proves: "The route and Help console use role-derived context, cited source-of-truth facts, Open Data decision context, deterministic no-key answers, and safe refusals for broken CAC-by-channel, PII, and Decision Queue bypass prompts.",
    status: "covered",
    requires: ["pure", "opendata"],
    tests: ["ask-agents.test.ts", "ask-route.test.ts", "rbac.test.ts › Ask-the-Hub"],
  },
  {
    id: "UC-GTC-CAMPAIGN",
    title: "GT Challenge stands up as a budgeted, threaded campaign",
    phase: "Phase 2 · Product",
    brief: "Worked example — “Stand it up as a campaign with budget… UTM captured.”",
    reqs: ["C4", "C7"],
    proves: "The gifted-quiz campaign threads across Meta insights and CRM source, ready to roll spend into a workstream.",
    status: "covered",
    requires: ["pure"],
    tests: ["brief-usecases.test.ts › UC-GTC-CAMPAIGN"],
  },
  {
    id: "UC-P2-AUTH-ROLES",
    title: "Auth + three roles enforced (Admin / Leader / Operator)",
    phase: "Phase 2 · Product",
    brief: "Non-negotiable — “Auth + three roles enforced… Role gating is a requirement, not a nicety.”",
    reqs: ["C1", "A5"],
    proves: "Deny-by-default app-level session + RBAC: unauthenticated requests get 401→/login; Admin/Leader/Operator are distinct identities; the Leader-only Decision Queue and Admin-only /dev surfaces are enforced at both the route policy and the Edge middleware; program scope derives from the session (not the client) and signed tokens reject tamper/expiry.",
    status: "covered",
    requires: ["pure"],
    tests: ["brief-usecases.test.ts › UC-P2-AUTH-ROLES", "rbac.test.ts › route policy / middleware / token integrity / program scope"],
  },
  {
    id: "UC-P2-HOME",
    title: "Composable Home widget library with role-aware starter pack",
    phase: "Phase 2 · Product",
    brief: "Non-negotiable — “Composable per-user Home: a widget library with a default starter pack, add/remove + saved layout per user.”",
    reqs: ["C5"],
    proves: "The 30+ widget library, PRD starter pack, and role-aware additions are modeled; saved per-user layout is tracked separately.",
    status: "covered",
    requires: ["pure"],
    tests: ["brief-usecases.test.ts › UC-P2-HOME", "phase2.test.ts › Phase 2 Home widget library"],
  },
  {
    id: "UC-P2-HOME-PERSISTENCE",
    title: "Composable Home saved layout persists per user",
    phase: "Phase 2 · Product",
    brief: "Non-negotiable — “add/remove + saved layout per user.”",
    reqs: ["C5", "C1"],
    proves: "Authenticated users save ordered widget arrays by session user id; add/remove/reorder helpers normalize the row and preserve saved empty layouts.",
    status: "covered",
    requires: ["pure"],
    tests: ["brief-usecases.test.ts › UC-P2-HOME-PERSISTENCE", "home-layout.test.ts › GET/PUT /api/home/layout persistence"],
  },
  {
    id: "UC-GTC-CAPTURE-ASSESS",
    title: "GT Challenge assess → route with consent and de-identification",
    phase: "Phase 2 · Product",
    brief: "Worked example — “Capture submissions… Let the program assess it… no submission lost, no double-counting.”",
    reqs: ["C6"],
    proves: "The assessment rejects non-consented submissions, buckets qualified leads, routes them to the right program, and emits a de-identified payload.",
    status: "covered",
    requires: ["pure"],
    tests: ["brief-usecases.test.ts › UC-GTC-CAPTURE-ASSESS", "phase2.test.ts › GT Challenge workflow"],
  },
  {
    id: "UC-GTC-CAPTURE-PERSIST",
    title: "GT Challenge public capture persists without double-counting",
    phase: "Phase 2 · Product",
    brief: "Worked example — “Capture submissions… no submission lost, no double-counting.”",
    reqs: ["C6"],
    proves: "The public capture contract is modeled without a live DB: consent is required before any save, an idempotency replay returns the original submission/lead, UTM is retained with `(not set)` fallback, and raw score/bucket/qualified persist with no negative gifted verdict. Remaining gap: replace the in-memory route store with a transactional DB adapter and additive migration.",
    status: "covered",
    requires: ["pure"],
    tests: ["brief-usecases.test.ts › UC-GTC-CAPTURE-PERSIST", "gt-challenge.test.ts › GT Challenge capture persistence model", "gt-challenge.test.ts › POST /api/gifted-quiz route contract"],
  },
  {
    id: "UC-P2-DECISION-RULING",
    title: "Leader ruling persists on an open Decision Queue item",
    phase: "Phase 2 · Product",
    brief: "Spec Module 11 — “approve / reject / need-info + comment text”; status Open → Decided → In-flight.",
    reqs: ["C2", "C6", "E3"],
    proves: "A Leader-only mutation applies approve/reject/need_info transitions, persists response fields, and rejects non-leaders or closed decisions.",
    status: "covered",
    requires: ["pure"],
    tests: ["decisions.test.ts › Decision Queue transitions", "decisions.test.ts › POST /api/decisions/[id]/decide"],
  },

  // ───────────────────────── Spec · Marketing Hub ─────────────────────────
  {
    id: "UC-SPEC-BUDGET-WORKSTREAMS",
    title: "Pre-loaded budget workstreams match the spec table",
    phase: "Spec · Marketing Hub",
    brief: "Spec Module 10 — Grassroots $210K, Content $90K, Guerrilla $40K, Foundations $25K = $365K.",
    reqs: ["C4", "D1"],
    proves: "Each workstream's recommended amount equals the spec's pre-loaded figure, summing to $365K.",
    status: "covered",
    requires: ["pure"],
    tests: ["brief-usecases.test.ts › UC-SPEC-BUDGET-WORKSTREAMS"],
  },
  {
    id: "UC-SPEC-CAMP-PL",
    title: "Summer camp is a separate P&L, not in the $365K budget",
    phase: "Spec · Marketing Hub",
    brief: "Spec Module 4 — “Camp is a separate P&L line — does not roll into Module 10 budget.”",
    reqs: ["C4", "C6"],
    proves: "No camp/summer workstream appears in the budget; camp registrations are tracked in their own feed.",
    status: "covered",
    requires: ["pure"],
    tests: ["brief-usecases.test.ts › UC-SPEC-CAMP-PL"],
  },
  {
    id: "UC-SPEC-FIELD-RELIABILITY",
    title: "Unreliable HubSpot fields flagged (TEFA, income, source)",
    phase: "Spec · Marketing Hub",
    brief: "Spec Module 7 — “Field reliability flags… TEFA, income, source… always visible.”",
    reqs: ["C8", "B4"],
    proves: "Exactly TEFA/income/source are modeled unreliable, and those fields actually drift out of parity.",
    status: "covered",
    requires: ["pure"],
    tests: ["brief-usecases.test.ts › UC-SPEC-FIELD-RELIABILITY"],
  },
  {
    id: "UC-SPEC-SCORE-CONVERSION",
    title: "Lead score correlates with conversion (validates the model)",
    phase: "Spec · Marketing Hub",
    brief: "Spec Module 7c — “score-to-conversion correlation (validates model)”; Module 5 engagement predictor.",
    reqs: ["C8", "D1"],
    proves: "Top-quartile lead scores deposit at a higher rate than bottom-quartile.",
    status: "covered",
    requires: ["pure"],
    tests: ["brief-usecases.test.ts › UC-SPEC-SCORE-CONVERSION"],
  },
  {
    id: "UC-SPEC-INCOME-MASTER",
    title: "Income is the master conversion variable",
    phase: "Spec · Marketing Hub",
    brief: "Spec Module 5 — “income is the master variable ($160K+ = ~25% conversion regardless of geography).”",
    reqs: ["D1"],
    proves: "$160K+ families convert at the highest rate across the modeled funnel.",
    status: "covered",
    requires: ["pure"],
    tests: ["seed.test.ts › makes income the master conversion variable"],
  },
  {
    id: "UC-SPEC-DQ-AUTODETECT",
    title: "CRM Ops auto-detects sync drift + UTM breakage",
    phase: "Spec · Marketing Hub",
    brief: "Spec Module 7e — “System auto-detects sync drift + UTM breakage and creates queue items automatically.”",
    reqs: ["B4", "C8"],
    proves: "The data-quality queue contains auto-generated UTM and sync issues (not manual-only).",
    status: "covered",
    requires: ["pure"],
    tests: ["brief-usecases.test.ts › UC-SPEC-DQ-AUTODETECT", "crm-ops.test.ts › CRM Ops · auto-detector"],
  },
  {
    id: "UC-SPEC-OUTBOX-DLQ",
    title: "Outbound sync has pending / done / dead-letter states",
    phase: "Spec · Marketing Hub",
    brief: "Spec Module 7 / Phase 1 — durable outbound sync with retries and dead-lettering.",
    reqs: ["B1", "B5"],
    proves: "The sync outbox models pending, done, and dead (failed-after-retries) entries.",
    status: "covered",
    requires: ["pure"],
    tests: ["brief-usecases.test.ts › UC-SPEC-OUTBOX-DLQ", "outbox-worker.test.ts"],
  },
  {
    id: "UC-SPEC-CONTENT-PIPELINE",
    title: "Content production pipeline has multiple stages",
    phase: "Spec · Marketing Hub",
    brief: "Spec Module 3 — “Concept → In production → Review → Scheduled → Published” (Google Sheet synced).",
    reqs: ["D1"],
    proves: "The stood-in content sheet carries rows across several pipeline stages, ending in published.",
    status: "covered",
    requires: ["pure"],
    tests: ["brief-usecases.test.ts › UC-SPEC-CONTENT-PIPELINE"],
  },
  {
    id: "UC-SPEC-XLINK-TESTIMONIAL",
    title: "Cross-link: testimonial → content production stub",
    phase: "Spec · Marketing Hub",
    brief: "Spec §4 — “Testimonial logged in Grassroots → auto-stub production card in Content.”",
    reqs: ["C6"],
    proves: "Logging a testimonial auto-creates a draft card in the Content pipeline.",
    status: "covered",
    requires: ["pure"],
    tests: ["brief-usecases.test.ts › UC-SPEC-XLINK-TESTIMONIAL"],
  },
  {
    id: "UC-SPEC-XLINK-OBJECTION",
    title: "Cross-link: top objection → content brief",
    phase: "Spec · Marketing Hub",
    brief: "Spec §4 — “Top objection in Admissions/VoC → auto-create content brief in Content.”",
    reqs: ["C6"],
    proves: "A high-frequency objection auto-generates a brief stub in the Content pipeline.",
    status: "covered",
    requires: ["pure"],
    tests: ["brief-usecases.test.ts › UC-SPEC-XLINK-OBJECTION"],
  },
  {
    id: "UC-SPEC-XLINK-HOTFAMILY",
    title: "Cross-link: hot family → Admissions/VoC + Decision Queue",
    phase: "Spec · Marketing Hub",
    brief: "Spec §4 — “Hot family flagged anywhere → chip in Admissions/VoC + Decision Queue.”",
    reqs: ["C6", "C2"],
    proves: "Flagging a hot family creates the Decision Queue payload and the module presenter exposes the Admissions + Decision Queue chip.",
    status: "covered",
    requires: ["pure"],
    tests: ["brief-usecases.test.ts › UC-SPEC-XLINK-HOTFAMILY"],
  },
  {
    id: "UC-SPEC-XLINK-EVENT",
    title: "Cross-link: parent-led event → Field Marketing (read-only)",
    phase: "Spec · Marketing Hub",
    brief: "Spec §4 / Module 2 — “Parent-led event created in Grassroots → read-only cross-link in Field Marketing.”",
    reqs: ["C6"],
    proves: "An ambassador-hosted event appears read-only in the Field Marketing calendar.",
    status: "covered",
    requires: ["pure"],
    tests: ["brief-usecases.test.ts › UC-SPEC-XLINK-EVENT"],
  },
  {
    id: "UC-SPEC-MONDAY-MEETING",
    title: "Shared scorecard drives the Monday meeting",
    phase: "Spec · Marketing Hub",
    brief: "Spec §5 / Module 6 — canonical weekly scorecard, identical for all users, mapped to the agenda.",
    reqs: ["C5", "C3"],
    proves: "Module 6 renders one shared, week-versioned scorecard that the whole agenda references.",
    status: "covered",
    requires: ["pure"],
    tests: ["brief-usecases.test.ts › UC-SPEC-MONDAY-MEETING"],
  },
  {
    id: "UC-SPEC-HANDOFF",
    title: "Marketing → onboarding handoff metric",
    phase: "Spec · Marketing Hub",
    brief: "Spec Modules 5/6 — handoff count, conversion rate, and velocity as a core KPI.",
    reqs: ["C3"],
    proves: "Handoff count/rate/velocity is computed from HubSpot deal-stage transitions.",
    status: "covered",
    requires: ["pure"],
    tests: ["brief-usecases.test.ts › UC-SPEC-HANDOFF"],
  },

  // ───────────────────────── Demo signals ─────────────────────────
  {
    id: "UC-DEMO-PAYMENT",
    title: "Watch a payment propagate without contamination",
    phase: "Demo signal",
    brief: "Show us it works — “watch a payment propagate.”",
    reqs: ["E1"],
    proves: "The /dev/payments watcher shows processed event state, payment status, idempotent replay/no-op, CRM handoff status, and program isolation/no-contamination. Live DB rows are used when available; deterministic seed facts keep the demo path visible without credentials.",
    status: "covered",
    requires: ["pure", "db", "stripe"],
    tests: ["payment-propagation-surface.test.ts", "payments.test.ts › succeeded PI propagates into the correct program, flips paid, enqueues outbox"],
  },
  {
    id: "UC-DEMO-BUDGET",
    title: "A budget reconcile to the total (logic)",
    phase: "Demo signal",
    brief: "Show us it works — “a budget reconcile to the total.”",
    reqs: ["E2"],
    proves: "Budget Tracker logic reconciles workstream rows to $365K and turns >10% variance into a Decision Queue item.",
    status: "covered",
    requires: ["pure"],
    tests: ["brief-usecases.test.ts › UC-DEMO-BUDGET", "phase2.test.ts › Phase 2 Budget Tracker", "budget.test.ts › Budget · reconcile to $365K + column identities"],
  },
  {
    id: "UC-DEMO-BUDGET-UI",
    title: "A budget reconcile to the total (UI)",
    phase: "Demo signal",
    brief: "Show us it works — “a budget reconcile to the total.”",
    reqs: ["E2", "C4"],
    proves: "Budget Tracker UI visibly shows workstream rows summing to $365K.",
    status: "covered",
    requires: ["pure"],
    tests: ["module-routes.test.ts › Budget route visibly reconciles workstreams to the $365K total and variance queue", "budget.test.ts › Budget · rendered sub-views"],
  },
  {
    id: "UC-DEMO-ROLE-DENIED",
    title: "A role denied the Decision Queue (policy/data)",
    phase: "Demo signal",
    brief: "Show us it works — “a role be denied the Decision Queue.”",
    reqs: ["E3", "C2"],
    proves: "Leader-only policy helpers expose the full queue to Leaders and filter it for non-leaders.",
    status: "covered",
    requires: ["pure"],
    tests: ["brief-usecases.test.ts › UC-DEMO-ROLE-DENIED", "phase2.test.ts › Phase 2 roles and Decision Queue gate"],
  },
  {
    id: "UC-DEMO-ROLE-DENIED-AUTH-UI",
    title: "A role denied the Decision Queue (route + UI)",
    phase: "Demo signal",
    brief: "Show us it works — “a role be denied the Decision Queue.”",
    reqs: ["E3", "C1", "C2"],
    proves: "The shared route policy blocks non-Leaders from the Decision Queue page, and the denied surface exposes no queue rows, counts, or ruling actions if rendered directly.",
    status: "covered",
    requires: ["pure"],
    tests: ["brief-usecases.test.ts › UC-DEMO-ROLE-DENIED-AUTH-UI", "rbac.test.ts › redirects an Operator away from the Decision Queue page"],
  },
  {
    id: "UC-DEMO-BANNER",
    title: "Data-confidence banner payload appears when parity drops",
    phase: "Demo signal",
    brief: "Show us it works — “the data-confidence banner appear when parity drops.”",
    reqs: ["E4"],
    proves: "Parity below threshold produces the banner payload, field-specific copy, and CRM Ops destination.",
    status: "covered",
    requires: ["pure"],
    tests: ["brief-usecases.test.ts › UC-DEMO-BANNER", "phase2.test.ts › Phase 2 CRM Ops and data-confidence banner", "crm-ops.test.ts › CRM Ops · banner alarm semantics"],
  },
  {
    id: "UC-DEMO-BANNER-UI",
    title: "Data-confidence banner renders across modules",
    phase: "Demo signal",
    brief: "Show us it works — “the data-confidence banner appear when parity drops.”",
    reqs: ["E4"],
    proves: "The banner renders across HubSpot-consuming modules when parity drops.",
    status: "covered",
    requires: ["pure"],
    tests: ["module-routes.test.ts › data-confidence banner renders on HubSpot-consuming module routes"],
  },
  {
    id: "UC-DEMO-OPENDATA",
    title: "A real Open Data query incl. a failure/edge case",
    phase: "Demo signal",
    brief: "Show us it works / What to submit — “a real Open Data query… including at least one failure/edge case.”",
    reqs: ["E5", "C7"],
    proves: "Live query works and degrades gracefully (cache → live → stale → fixture), with the source reported.",
    status: "covered",
    requires: ["opendata", "pure"],
    tests: ["opendata.test.ts › cache/stale/fixture failure paths", "opendata-route.test.ts › 502 failure path"],
  },
];

export function getUseCasesByPhase(): { phase: UseCasePhase; items: UseCase[] }[] {
  return UC_PHASES.map((phase) => ({
    phase,
    items: USE_CASES.filter((u) => u.phase === phase),
  })).filter((g) => g.items.length > 0);
}

export function getUseCaseCounts() {
  const by = (s: UseCaseStatus) => USE_CASES.filter((u) => u.status === s).length;
  return {
    total: USE_CASES.length,
    covered: by("covered"),
    live: by("live"),
    pending: by("pending"),
  };
}
